Repository publiclab/plots2, pull requests merged in 2018-02, with the labels that each got.

#2283 Unnecessary hr removed on profile page
  app/views/users/profile.html.erb
Labels: ready

#2273 Question error message duplicacy removed
  app/models/node.rb
  test/functional/notes_controller_test.rb
Labels: ready

#2320 Include mysql configuration file (supersedes #1428)
  config/my.cnf
  docker-compose.yml
Labels: in progress

#2222 added link to questions on home page
  app/views/home/home.html.erb
Labels: ready

#2263 added count of research notes and comments on profile page
  app/controllers/users_controller.rb
  app/views/users/profile.html.erb
Labels: review-me

#2317 Align read more button
  app/views/notes/_notes.html.erb
Labels: review-me

#2349 Redundant gemfile.new deleted
  Gemfile.new
Labels: ready

#2342 Chat should hover on hovering
  app/views/layouts/_header.html.erb
Labels: ready

#2329 Fixed issue #2328 positioning of social media buttons in wiki page
  app/views/home/_social.html.erb
Labels: ready

#2327 Edit home action in home controller
  app/controllers/home_controller.rb
Labels: ready

#2238 Remove duplicate ids in signin and signup page
  app/views/layouts/_header.html.erb
  app/views/user_sessions/new.html.erb
Labels: ready

#2286 Added functional test for subscribing to a tag.
  test/functional/subscription_controller_test.rb
Labels: review-me

#2251 Added scroll to top in footer
  app/assets/javascripts/application.js
  app/assets/javascripts/header_footer.js
  app/assets/stylesheets/style.css
  app/views/layouts/_footer.html.erb
Labels: review-me

#2247 banned users are visible to /people page for admin
  app/controllers/users_controller.rb
  app/views/users/list.html.erb
Labels: review-me

#2362 Wiki pages with 0 likes shown on /wiki/liked
  app/controllers/wiki_controller.rb
Labels: ready

#2360 added links for location privacy help page #2346
  Gemfile.lock
  app/views/map/_peopleLeaflet.html.erb
  app/views/map/_userLeaflet.html.erb
Labels: ready

#2288 fixed search error
  app/views/layouts/_header.html.erb
Labels: review-me

#2323 Wiki pages with CRUD as title should not be published
  app/models/node.rb
  test/unit/node_test.rb
Labels: ready

#2302 Research and dashboard corrected
  app/controllers/home_controller.rb
  config/routes.rb
  test/functional/home_controller_test.rb
Labels: ready

#2253 Changes tag follow popover
  app/assets/stylesheets/application.css
  app/assets/stylesheets/tags.css
Labels: review-me

#2373 Migration for changing comment status
  db/migrate/20180220180926_add_default_value_to_comment_status.rb
  db/schema.rb.example
Labels: in progress

#2305 Comment spam moderation Part 2
  app/controllers/admin_controller.rb
  app/models/comment.rb
  test/fixtures/comments.yml
  test/functional/admin_controller_test.rb
  test/functional/notes_controller_test.rb
  test/unit/node_test.rb
Labels: ready

#2384 Shows Autocomplete drop-down (Fixes #2186)
  app/views/layouts/application.html.erb
Labels: in progress

#2390 ga fixes
  app/assets/javascripts/application.js
  app/assets/javascripts/google_analytics.js
  app/views/layouts/_google_analytics.html.erb
Labels: in progress

#2391 Delete location_tags.js
  app/assets/javascripts/application.js
  app/assets/javascripts/location_tags.js
Labels: in progress

#2406 Adding feature to allow raw HTML pages
  app/models/node.rb
  app/models/revision.rb
  app/views/wiki/show.html.erb
Labels: in progress

#2381 Added omniauth gem and facebook-omniauth gem
  Gemfile
Labels: ready

#2374 Pagination and sorting of digest by recency
  app/controllers/subscription_controller.rb
  app/models/user.rb
Labels: ready

#2276 Added search validation for wiki sidebar search
  app/views/dashboard/_wiki.html.erb
Labels: review-me
