Repository publiclab/plots2, pull requests merged in 2018-06, with the labels that each got.

#2284 Added link for "adding descriptive tags"
  app/views/wiki/_header.html.erb
  config/locales/views/wiki/show/en.yml
Labels: ready

#2751 Commands to redeploy running container
  Makefile
Labels: in progress

#2749 Fix Like count error
  app/models/node.rb
  db/migrate/20180525220718_remove_node_selections_of_deleted_nodes.rb
  db/schema.rb.example
  test/unit/node_test.rb
Labels: ready

#2476 Add a feedback notice to "i did this" buttons.
  app/views/notes/_responses.html.erb
Labels: first-timers-only, ready

#2562 Update users_controller.rb to require login before edit
  app/controllers/users_controller.rb
  test/functional/users_controller_test.rb
  test/integration/routes_test.rb
Labels: in progress, in-progress

#2711 digest email initial functionality
  app/controllers/users_controller.rb
  app/jobs/digest_mail_job.rb
  app/mailers/subscription_mailer.rb
  app/models/user.rb
  app/views/subscription_mailer/send_digest.html.erb
  app/views/users/profile.html.erb
  config/routes.rb
  test/functional/users_controller_test.rb
  test/jobs/digest_mail_job_test.rb
Labels: ready, summer-of-code

#2737 User should not be able to create Oauth based user_tags
  app/controllers/admin_controller.rb
  app/controllers/relationships_controller.rb
  app/controllers/user_tags_controller.rb
  app/models/node.rb
Labels: summer-of-code

#2747 Submitting a draft
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/controllers/notes_controller.rb
  app/models/node.rb
  app/models/user.rb
  app/views/dashboard/_node_default.html.erb
  app/views/editor/rich.html.erb
  bower.json
  config/routes.rb
  test/fixtures/node_tags.yml
  test/fixtures/nodes.yml
  test/fixtures/revisions.yml
  test/fixtures/tags.yml
  test/functional/notes_controller_test.rb
Labels: enhancement, feature, review-me, summer-of-code

#2675 enable method=post for data-url image upload at /post
  app/controllers/editor_controller.rb
  app/models/image.rb
  config/routes.rb
Labels: in progress

#2553 Improved translate widget
  app/views/sidebar/_related.html.erb
Labels: review-me

#2767 List subscription change
  app/controllers/users_controller.rb
Labels: in progress

#2738 Add sidekiq gem
  Gemfile
  app/controllers/admin_controller.rb
  app/controllers/relationships_controller.rb
  config/application.rb
  config/initializers/sidekiq.rb
  docker-compose.yml
Labels: ready, summer-of-code

#2734 Place tag detection and replacing "-" with ""
  app/assets/javascripts/tagging.js
Labels: in progress

#2770 make descriptive tag links move to bottom of page- issue #2768
  app/views/notes/show.html.erb
  config/locales/views/notes/show/en.yml
Labels: ready

#2773 Skylight performance tracking
  Gemfile
  Gemfile.lock
  config/skylight.yml
Labels: in progress

#2669 Reply to comment by email feature
  Gemfile
  Gemfile.lock
  app/mailers/comment_mailer.rb
  app/mailers/subscription_mailer.rb
  app/models/comment.rb
  app/models/node.rb
  app/views/notes/_comment.html.erb
  db/migrate/20180605000000_add_comment_via_column_to_comment.rb
  db/migrate/20180605010014_add_message_id_column_to_comments.rb
  db/schema.rb.example
  script/mailman_server
  test/functional/admin_controller_test.rb
  test/functional/comment_controller_test.rb
  test/functional/notes_controller_test.rb
  test/unit/comment_mailer_test.rb
  test/unit/subscription_mailer_test.rb
Labels: review-me, summer-of-code

#2780 Whenever cron update command in Makefile for redeploy-container
  Makefile
Labels: ready, summer-of-code

#2784 Fix rss images and email images
  app/views/notes/rss.rss.builder
  app/views/subscription_mailer/notify_node_creation.html.erb
  app/views/tag/rss.rss.builder
  app/views/tag/rss_for_tagged_with_author.rss.builder
  app/views/users/rss.rss.builder
Labels: in progress

#2557 Fixed issue#2445 added both direction sort order
  app/controllers/tag_controller.rb
  app/views/tag/index.html.erb
Labels: in progress

#2788 Changed get to post
  config/routes.rb
Labels: in progress

#2791 Update container definitions to match actual files used.
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
Labels: in progress

#2753 Index page listing for UserTags per issue #2741.
  app/controllers/user_tags_controller.rb
  app/views/user_tags/index.html.erb
  config/routes.rb
  test/functional/user_tags_controller_test.rb
Labels: in progress

#2804 Update routes.rb for wiki update
  app/views/layouts/_footer.html.erb
  config/routes.rb
  test/integration/wiki_creation_test.rb
Labels: in progress

#2806 integration tests for assets
  app/controllers/admin_controller.rb
  app/views/admin/assets.html.erb
  config/initializers/assets.rb
  config/routes.rb
  test/integration/public_pages_test.rb
Labels: in progress

#2808 Added routes to notes/edit
  config/routes.rb
  test/functional/notes_controller_test.rb
Labels: bug, in progress

#2810 Openid POST fix
  config/routes.rb
Labels: in progress

#2794 fixing error in home_controller related to `group by`
  app/controllers/home_controller.rb
Labels: in progress

#2816 Update Dangerfile to remove smart quotes
  Dangerfile
Labels: in progress

#2818 Update routes.rb to fix embeddable features
  config/routes.rb
  test/functional/features_controller_test.rb
Labels: in progress

#2820 Delete route for notes
  config/routes.rb
Labels: in progress

#2774 Documentation for the reply-by-email to comment feature
  README.md
  doc/EMAIL.md
Labels: documentation, in progress, summer-of-code

#2834 Re-order comment options and messages
  app/views/notes/_comment.html.erb
Labels: ready

#2257 encoding issue resolved for migrating DrupalUsers to User records
  app/models/drupal_user.rb
  db/migrate/20180614000000_add_user_for_orphaned_drupal_user.rb
  db/schema.rb.example
Labels: ready

#2832 Emoji autocomplete
  app/assets/javascripts/application.js
  app/assets/stylesheets/comments.css
  app/helpers/application_helper.rb
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  config/initializers/assets.rb
Labels: ready

#2844 Fix parent powertags for wikis like /barnraising
  app/views/wiki/_header.html.erb
Labels: in progress

#2868 fixed migration bug
  db/migrate/20180614000000_add_user_for_orphaned_drupal_user.rb
  db/schema.rb.example
Labels: in progress

#2869 Like with emoji
  app/controllers/comment_controller.rb
  app/helpers/application_helper.rb
  app/models/comment.rb
  app/views/comment/like_comment.js.erb
  app/views/notes/_comment.html.erb
  app/views/notes/_comments.html.erb
  db/migrate/20180618184048_add_emoji_type_to_like.rb
  db/schema.rb.example
Labels: in progress

#2864 Query should search for extra tag while searching
  app/controllers/tag_controller.rb
Labels: review-me

#2771 Google Authentication
  .gitignore
  app/controllers/application_controller.rb
  app/controllers/user_sessions_controller.rb
  app/controllers/user_tags_controller.rb
  app/controllers/users_controller.rb
  app/models/node.rb
  app/models/user.rb
  app/models/user_tag.rb
  app/views/layouts/_header.html.erb
  app/views/user_sessions/new.html.erb
  app/views/users/edit.html.erb
  config/environments/test.rb
  config/initializers/omniauth.rb
  config/routes.rb
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
  test/fixtures/user_tags.yml
  test/functional/user_sessions_controller_test.rb
  test/integration/login_flow_test.rb
  test/unit/user_tag_test.rb
  test/unit/user_test.rb
Labels: design, enhancement, feature, review-me, summer-of-code

#2827 Include needed environment variables
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
Labels: in progress

#2798 Rails 5.1 upgrade
  Gemfile
  Gemfile.lock
  app/controllers/openid_controller.rb
  app/views/admin/assets.html.erb
  app/views/questions/index.html.erb
  test/functional/features_controller_test.rb
  test/functional/notes_controller_test.rb
  test/functional/user_tags_controller_test.rb
  test/functional/wiki_controller_test.rb
Labels: ready, summer-of-code

#2875 Docker changes made for Github Provider
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
Labels: review-me, summer-of-code

#2865 Debian stretch (fixes #2811)
  Dockerfile
Labels: in progress

#2883 Corrected the tests which are failing due to passing of parameters
  test/functional/user_sessions_controller_test.rb
Labels: in progress

#2823 Add Mailman service to docker compose
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
Labels: in progress, review-me, summer-of-code

#2885 Changed path for mailman build and app in docker-compose-*
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
Labels: in progress

#2887 Removed routing errors related to questions comment and answers
  config/routes.rb
Labels: in progress

#2890 Ignore standard input for mailman
  script/mailman_server
Labels: in progress

#2858 Added fontawesome icon to edit view
  app/views/users/edit.html.erb
Labels: review-me, summer-of-code

#2897 PATCH to add network_mode host in docker-compose-* for specifying network host
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
  script/mailman_server
Labels: in progress

#2900 Added some routing tests for the new routes created
  test/integration/routes_test.rb
Labels: in progress

#2860 Added login google button for OAuth
  app/views/user_sessions/new.html.erb
Labels: ready, summer-of-code

#2855 Documentation added for OAuth
  doc/Omniauth.md
Labels: documentation, ready, summer-of-code

#2861 Google icon added to signup view
  app/views/users/new.html.erb
Labels: review-me, summer-of-code

#2859 Google button added to header for OAuth
  app/views/layouts/_header.html.erb
Labels: enhancement, ready, summer-of-code

#2874 Added OAuth hash for testing Github provider
  config/environments/test.rb
Labels: ready, summer-of-code

#2908 Update 'learn more' link near draft checkbox (#2904)
  app/views/editor/rich.html.erb
Labels: ready

#2906 Update not working issue
  app/controllers/comment_controller.rb
  app/controllers/images_controller.rb
  app/controllers/notes_controller.rb
  app/controllers/tag_controller.rb
  app/controllers/wiki_controller.rb
  test/functional/images_controller_test.rb
  test/functional/notes_controller_test.rb
  test/functional/tag_controller_test.rb
  test/functional/wiki_controller_test.rb
Labels: ready

#2501 social link styling in profile page
  app/views/users/profile.html.erb
Labels: ready

#2912 Resolved Mailman database service connect errors in docker
  app/models/comment.rb
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
  script/mailman_server
Labels: in progress, summer-of-code

#2916 dep update for sprockets
  Gemfile.lock
Labels: in progress

#2888 Mailman server log file path change
  doc/EMAIL.md
  script/mailman_server
Labels: in progress, ready

#2825 Change like count to avoid flickering to fix issue #2656
  app/controllers/like_controller.rb
  test/functional/like_controller_test.rb
Labels: ready

#2914 Integration tests added for Github Provider
  test/integration/login_flow_test.rb
Labels: review-me

#2829 Ajax notifications
  app/assets/javascripts/application.js
  app/assets/javascripts/like.js
  app/assets/javascripts/noty_notification.js
  app/assets/stylesheets/application.css
  app/views/comment/create.js.erb
  app/views/comment/delete.js.erb
  app/views/comment/like_comment.js.erb
  app/views/comments/_form.html.erb
  app/views/notes/_comment.html.erb
  app/views/notes/_comments.html.erb
  app/views/notes/show.html.erb
  bower.json
Labels: ready

#2926 Toopltip added to show users who reacted on a comment
  .gitignore
  app/models/comment.rb
  app/models/like.rb
  app/views/notes/_comment.html.erb
  test/unit/comment_test.rb
Labels: in progress, summer-of-code

#2915 User session controller tests for github provider
  config/environments/test.rb
  test/functional/user_sessions_controller_test.rb
Labels: ready

#2881 Rename docker-compose.yml to containers/docker-compose-testing.yml
  .travis.yml
  containers/docker-compose-testing.yml
Labels: in progress

#2923 Changed _header.html.erb to not accept edits from newcomers
  app/views/wiki/_header.html.erb
Labels: ready

#2909 Follow user by Follow button on notes
  app/controllers/relationships_controller.rb
  app/views/like/_like.html.erb
Labels: review-me

#2934 Change do-not-reply@ to notifications@
  app/mailers/admin_mailer.rb
  app/mailers/answer_mailer.rb
  app/mailers/comment_mailer.rb
  app/mailers/password_reset_mailer.rb
  app/mailers/subscription_mailer.rb
  app/mailers/welcome_mailer.rb
  app/views/tag/icalendar.ics.erb
  test/unit/answer_mailer_test.rb
  test/unit/comment_mailer_test.rb
  test/unit/subscription_mailer_test.rb
Labels: ready, summer-of-code

#2879 fixes Issue 2646 - made changes to cloud9 install instructions
  install_cloudnine.sh
Labels: in progress

#2936 Update _sidebar.html.erb
  app/views/dashboard/_sidebar.html.erb
Labels: in progress

#2938 Don't allow new users to use '/wiki/new'
  app/controllers/wiki_controller.rb
  test/functional/wiki_controller_test.rb
Labels: ready

#2942 Fixing some routing errors
  config/routes.rb
Labels: in progress

#2943 Added tests for routes fixes
  test/integration/routes_test.rb
Labels: in progress

#2937 Debugged Development Error for OAuth
  app/views/layouts/_header.html.erb
  app/views/user_sessions/new.html.erb
  app/views/users/edit.html.erb
  app/views/users/new.html.erb
  doc/Omniauth.md
Labels: ready

#2946 blog on front page
  app/assets/javascripts/application.js
  app/controllers/home_controller.rb
  app/views/home/home.html.erb
Labels: in progress

#2947 Docker changes for the Twitter Provider
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
Labels: ready

#2949 Repositioned some routes
  config/routes.rb
Labels: in progress

#2950 fix nilClass error for emoji likes
  app/models/comment.rb
Labels: in progress

#2951 added routes for answer deletion
  config/routes.rb
  test/integration/routes_test.rb
Labels: in progress

#2948 Twitter Provider Initializer changes
  config/initializers/omniauth.rb
Labels: ready

#2955 Update en.yml
  config/locales/controllers/users_controller/en.yml
Labels: in progress

#2835 Sharing draft via secret URL
  app/controllers/application_controller.rb
  app/controllers/notes_controller.rb
  app/models/node.rb
  app/views/notes/show.html.erb
  config/routes.rb
  test/fixtures/nodes.yml
  test/functional/notes_controller_test.rb
Labels: ready, summer-of-code

#2956 Rearranging tabs on profile page
  app/controllers/users_controller.rb
  app/views/notes/_coauthored_notes.html.erb
  app/views/notes/_draft_notes.html.erb
  app/views/notes/_notes.html.erb
  app/views/users/_likes.html.erb
  app/views/users/profile.html.erb
Labels: ready
