Repository publiclab/plots2, pull requests merged in 2018-09, with the labels that each got.

#3288 Add passenger precompile nginx step (fixes #3287)
  Dockerfile
Labels: in progress

#3290 Revert "Add passenger precompile nginx step (fixes #3287)"
  Dockerfile
Labels: in progress

#3286 Adding sort_by=recent as default in search/all-> profiles
  app/services/search_criteria.rb
  app/services/search_service.rb
Labels: API, in progress, review-me

#3291 Revert "Revert "Add passenger precompile nginx step (fixes #3287)""
  Dockerfile
Labels: in progress

#3293 Remove tracing used for debug. (Should improve speed).
  .gitlab-ci.yml
  Dockerfile
Labels: in progress

#3292 Removing hash from inline maps
  app/views/map/_leaflet.html.erb
Labels: ready

#3230 listing of nodes with multiple tags - Add cleanup
  app/views/tag/show.html.erb
  app/views/tag/show/_contributors.html.erb
  app/views/tag/show/_header.html.erb
  app/views/tag/show/_nav_tabs.html.erb
  app/views/tag/show/_questions.html.erb
  app/views/tag/show/_related_tags.html.erb
  app/views/tag/show/_tab_content.html.erb
  app/views/tag/show/_user_controls.html.erb
Labels: ready

#2659 Yarn transition work-in-progress
  .bowerrc
  .gitlab-ci.yml
  .travis.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  Makefile
  bower.json
  package.json
  yarn.lock
Labels: in progress

#3282 Adding Boolean mode option to node.search()
  app/controllers/searches_controller.rb
  app/models/node.rb
  app/services/search_service.rb
Labels: API, in progress, review-me, rgsoc, summer-of-code

#3304 Search ui improvement
  app/assets/javascripts/restful_typeahead.js
  app/assets/stylesheets/style.css
  app/models/doc_result.rb
  app/services/search_service.rb
  app/views/layouts/_header.html.erb
  app/views/searches/new.html.erb
  config/locales/views/layouts/_header/en.yml
  test/unit/api/search_service_full_text_search_test.rb
  test/unit/api/search_service_test.rb
  test/unit/doc_result_test.rb
  test/unit/helpers/search_helper_test.rb
Labels: review-me, rgsoc

#3309 Comparing search modes (boolean and natural)
  app/views/searches/results.html.erb
  test/integration/search_flow_test.rb
Labels: in progress, rgsoc

#3318 Update package.json to upgrade packages
  package.json
Labels: in progress

#3274 Update README.md
  README.md
Labels: in progress

#3335 Added "Reply to this email to post a response" to various email templates
  app/views/comment_mailer/notify.html.erb
Labels: in progress

#3365 Welcome message on dashboard improved
  app/views/dashboard/dashboard.html.erb
Labels: ready

#3376 Set mailman container to restart upon failure (workaround for #3208)
  containers/docker-compose-production.yml
Labels: ready

#3377 Set request queue limit to 200 (default 100)
  containers/docker-compose-production.yml
Labels: in progress

#3380 index for impressionist gem
  db/migrate/20180921210045_add_impressions_ip_index.rb
  db/schema.rb.example
Labels: in progress

#3392 Added Heading on the search page
  app/views/search/new.html.erb
Labels: ready

#3389 updated profile url issue on Search profiles view
  app/views/search/profiles.html.erb
Labels: ready

#3400 Add-about-active-contribution-of-public-lab
  README.md
Labels: ready

#3413 Changed toggle UI button CSS for conversation thread in comments.
  app/views/notes/_comment.html.erb
Labels: ready

#3402 fixes #3396 (Deleted dynamic_search.js and updated assets.rb)
  app/assets/javascripts/dynamic_search.js
  config/initializers/assets.rb
Labels: ready

#3446 Reduce pool size to 8
  containers/docker-compose-production.yml
Labels: in progress

#3445 Profiles method only join nodes where(node_revisions.status = 1)
  app/services/search_service.rb
Labels: in progress, ready

#3461 Link GCI Wiki to readme
  README.md
Labels: ready

#3483 Add doc for running plots2 with MySQL
  doc/TESTING.md
Labels: documentation, in progress, ready

#3508 Update api docs
  doc/API.md
Labels: documentation

#3519 Change API params to ruby standard
  app/api/srch/search.rb
  app/api/srch/shared_params.rb
  app/assets/javascripts/atwho_autocomplete.js
  app/assets/javascripts/restful_typeahead.js
  app/models/search_request.rb
  app/services/search_criteria.rb
  app/services/search_service.rb
  app/views/editor/questionRich.html.erb
  app/views/editor/rich.html.erb
  app/views/editor/wikiRich.html.erb
  app/views/map/_leaflet.html.erb
  app/views/map/_peopleLeaflet.html.erb
  doc/API.md
  test/functional/api/search_api_full_text_test.rb
  test/functional/api/search_api_test.rb
  test/unit/api/search_service_full_text_search_test.rb
  test/unit/api/search_service_test.rb
Labels: in progress, review-me, rgsoc

#3529 change doc variables after changing DocResult params to snake case
  app/assets/javascripts/atwho_autocomplete.js
  app/views/editor/questionRich.html.erb
  app/views/editor/rich.html.erb
  app/views/editor/wikiRich.html.erb
  app/views/map/_leaflet.html.erb
  app/views/map/_peopleLeaflet.html.erb
  test/functional/api/search_api_full_text_test.rb
Labels: bug, in progress, review-me

#3467 Turn Google Maps API key into environment parameter
  app/views/layouts/application.html.erb
Labels: in progress

#3514 test locale change
  config/locales/controllers/application_controller/en.yml
  config/locales/en.yml
  config/locales/views/dashboard/_activity/en.yml
Labels: in progress
