Repository publiclab/plots2, pull requests merged in 2018-11, with the labels that each got.

#3881 Reduce worker process count
  containers/docker-compose-production.yml
Labels: in progress

#3812 Add forward stat page
  app/views/stats/index.html.erb
  config/locales/en.yml
  config/locales/views/notes/stats/en.yml
Labels: ready

#3855 Move commenting UI code into an independent .js file. Fixes #3831.
  app/assets/javascripts/comment.js
  app/views/comments/_form.html.erb
  config/initializers/assets.rb
Labels: ready

#3910 Initial docs for containers
  doc/CONTAINERS.md
Labels: in progress

#3933 Update _advanced_tagging.html.erb
  app/assets/javascripts/tagging.js
  app/views/notes/show.html.erb
  app/views/tag/_advanced_tagging.html.erb
Labels: in progress

#3884 Ensure preservation of return_to through OAuth login flow
  app/controllers/user_sessions_controller.rb
  app/views/layouts/_header.html.erb
  app/views/layouts/_social_icons.html.erb
Labels: ready

#3939 Set mailman to always restart
  containers/docker-compose-production.yml
Labels: in progress

#3940 add decimals to map queries
  app/views/map/_leaflet.html.erb
Labels: in progress

#3883 Split create function into two login paths
  app/controllers/user_sessions_controller.rb
  app/views/layouts/_header.html.erb
  app/views/layouts/_social_icons.html.erb
Labels: in progress

#3700 Update docs and add tests for the taglocations API method - fix #3597
  app/models/node.rb
  app/models/user.rb
  app/services/search_service.rb
  doc/API.md
  test/functional/api/search_api_test.rb
  test/unit/api/search_service_test.rb
Labels: in progress

#3969 Load some maps near people's marked location if it exists #3965
  app/controllers/map_controller.rb
  app/controllers/users_controller.rb
  app/views/map/_peopleLeaflet.html.erb
  app/views/map/index.html.erb
Labels: in progress

#3987 alternative verificaiton spamaway
  app/views/users/_form.html.erb
  config/locales/models/spamaway/zh-cn.yml
  config/locales/views/users/_form/zh-cn.yml
Labels: in progress

#3983 rescue from failed welcomemailer
  app/controllers/users_controller.rb
Labels: in progress

#3989 alternative recaptcha questions
  config/locales/models/spamaway/en.yml
  config/locales/views/users/_form/en.yml
Labels: in progress

#3990 added zh-cn locale
  app/views/users/_form.html.erb
  app/views/users/_spamaway.html.erb
  config/application.rb
  config/locales/models/spamaway/zh-CN.yml
  config/locales/views/users/_form/en.yml
  config/locales/views/users/_form/zh-CN.yml
Labels: in progress

#3991 Integration of new LEL feature - spinner .
  app/views/map/_leaflet.html.erb
  app/views/map/_peopleLeaflet.html.erb
  app/views/map/_userLeaflet.html.erb
  package.json
Labels: in progress

#3981 Created LABELS.md
  doc/LABELS.md
Labels: ready

#3980 Change Show more/less
  app/views/grids/_notes.html.erb
Labels: ready

#3963 Trending tags showing duplicates
  app/models/tag.rb
Labels: ready

#4007 Added integration tests from unit test file [Resolves #3432]
  test/integration/incoming_mail_parsing_test/yahoo_parsing_test.rb
  test/integration/token_comment_test.rb
  test/unit/comment_test.rb
Labels: ready

#3541 Added first_time_commenters function
  app/models/user.rb
Labels: ready

#3330 SMTP test start
  app/controllers/admin_controller.rb
  config/routes.rb
Labels: in progress

#3794 Adding a test to people nearby search method and sort people by recent signups [WIP]
  app/api/srch/search.rb
  app/services/execute_search.rb
  app/services/search_service.rb
  test/fixtures/user_tags.yml
  test/functional/api/search_api_test.rb
  test/unit/api/search_service_test.rb
Labels: ready

#4022 removed auto-added aesterisk in boolean search
  app/models/node.rb
Labels: ready

#3813 Removed Donate under Get Involved completely
  app/views/layouts/_header.html.erb
Labels: ready

#4056 Combined wiki/note grids
  test/unit/node_shared_test.rb
Labels: ready

#4055 Fix autocomplete on post pages
  app/views/editor/questionRich.html.erb
  app/views/editor/rich.html.erb
  app/views/editor/wikiRich.html.erb
Labels: ready

#4021 Access Token Popup (GCI)
  app/views/users/_token.html.erb
  app/views/users/profile.html.erb
Labels: ready

#4010 Same format to delete comment and answer
  app/views/questions/_answer.html.erb
Labels: ready

#4028 Moved all files from app/views/comment to app/view/comments
  app/controllers/comment_controller.rb
  app/views/comments/create.html.erb
  app/views/comments/create.js.erb
  app/views/comments/delete.js.erb
  app/views/comments/like_comment.js.erb
  app/views/comments/make_answer.js.erb
  config/routes.rb
  test/functional/comment_controller_test.rb
Labels: ready

#3711 Add all content search tab which displays all the content matching the query
  app/controllers/search_controller.rb
  app/helpers/search_helper.rb
  app/views/search/all_content.html.erb
  config/routes.rb
  test/functional/search_controller_test.rb
Labels: in-progress, review-me

#4025 [WIP] Render SMTP test result in plain text
  app/controllers/admin_controller.rb
Labels: in progress

#3941 Issue3890
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/first-timers-issue-template.md
Labels: ready

#3642 add child page link to sidebar
  app/views/sidebar/_related.html.erb
Labels: fto-candidate, review-me

#4015 Search field is made required
  .gitignore
  app/views/tag/_sorting.html.erb
Labels: in progress

#4078 breakout-questions
  app/views/notes/_comment.html.erb
Labels: in progress

#4081 Inline wiki table formatting broken
  app/views/grids/_wikis.html.erb
  app/views/notes/_comment.html.erb
  config/locales/views/wiki/revisions/en.yml
Labels: in progress

#4084 tag fix for non-existent tags
  app/views/tag/show.html.erb
  test/functional/tag_controller_test.rb
Labels: in progress

#4086 Comment display on /comments
  app/controllers/comment_controller.rb
Labels: in progress

#4085 Test for power tag embedded grids
  app/controllers/tag_controller.rb
  app/views/grids/_nodes.html.erb
  test/functional/tag_controller_test.rb
Labels: in progress
