Repository publiclab/plots2, pull requests merged in 2018-12, with the labels that each got.

#4087 fixes to question search
  app/api/srch/search.rb
  app/services/execute_search.rb
Labels: in progress

#4006 Improve in questions page when search questions by topic
  app/views/tag/_sorting.html.erb
Labels: in progress

#3903 Remove redundancy of 'new_contributor' code
  app/models/drupal_user.rb
  app/models/node_tag.rb
  test/unit/tag_test.rb
Labels: in progress

#4088 updated js deps with Yarn
  package.json
  yarn.lock
Labels: in progress

#4090 Spinner patch for /maps !
  app/views/map/index.html.erb
Labels: ready

#4097 Delete questions/_comment.html.erb
  app/views/questions/_comment.html.erb
Labels: in progress

#4095 fileupload update
  package.json
  yarn.lock
Labels: in progress

#4096 Fix and test for inline grids in comments
  app/views/notes/_comment.html.erb
  test/functional/comment_controller_test.rb
Labels: in progress

#4103 Unit tests for reply-by-email feature functions in comment model
  test/unit/comment_test.rb
Labels: in progress, ready

#4098 Email to moderators (create a comment_moderation mailer)
  app/mailers/admin_mailer.rb
  app/models/comment.rb
  app/models/node.rb
  app/models/user.rb
  app/views/admin_mailer/notify_comment_moderators.html.erb
  test/fixtures/drupal_users.yml
  test/fixtures/users.yml
  test/functional/comment_controller_test.rb
  test/unit/admin_mailer_test.rb
Labels: in-progress

#4148 OAuth shown in development mode
  app/views/user_sessions/new.html.erb
  app/views/users/_form.html.erb
Labels: in progress

#4150 Refine new_contributor code in user.rb
  app/models/user.rb
Labels: in progress

#4166 Brainstorm Label added
  doc/LABELS.md
Labels: in progress

#4136 /api/srch/profiles: search only by user tag
  app/api/srch/search.rb
  app/services/search_service.rb
  doc/API.md
Labels: in progress, ready

#4185 Login button for the modal fixed
  app/views/user_sessions/_new.html.erb
Labels: in progress

#4197 Return_to fixed
  app/views/user_sessions/_new.html.erb
Labels: in progress

#4216 Added login modal for answers at /questions
  app/views/questions/_answers.html.erb
Labels: ready

#4249 Question page title stays after login on questions
  app/views/questions/index.html.erb
Labels: ready

#4239 Add modal for ask question on wikis page
  app/views/grids/_notes.html.erb
Labels: ready

#4260 Update header.html.erb
  app/views/layouts/_header.html.erb
Labels: ready

#4182 Add delay (350ms) to typeahead search
  app/assets/javascripts/restful_typeahead.js
Labels: ready

#4223 Style Comments to Include Grey Background
  app/views/comments/_form.html.erb
Labels: in progress

#4211 Add Login Modal on "Join Public Lab" link
  app/views/dashboard/_header.html.erb
  test/fixtures/node_tags.yml
Labels: ready

#4219 Create a moderated view for the comment
  app/controllers/admin_controller.rb
  app/controllers/home_controller.rb
  app/views/dashboard/_comment_moderate.html.erb
  app/views/dashboard/_node_comment.html.erb
  app/views/dashboard/_node_moderate.html.erb
  config/locales/views/dashboard/_node_moderate/en.yml
  test/integration/I18n_test.rb
Labels: in progress

#4198 Fix Aspect Ratio For Images
  app/assets/stylesheets/style.css
Labels: in progress

#4266 Trending tags showing duplicates: group only by name
  app/models/tag.rb
Labels: in progress, ready

#4226 Create a comment_moderation mailer - Email to moderators approval part
  app/controllers/admin_controller.rb
  app/mailers/admin_mailer.rb
  app/views/admin_mailer/notify_moderators_of_comment_approval.html.erb
  test/functional/admin_controller_test.rb
  test/unit/admin_mailer_test.rb
Labels: ready

#4144 Add a blank map and prompt people to add location to un-geotagged note pages [WIP]
  app/views/layouts/_footer.html.erb
  app/views/sidebar/_related.html.erb
Labels: review-me

#4276 Fix uncentered pagination
  app/views/tag/index.html.erb
Labels: in progress, ready

#4305 user.send_digest_email unit test
  test/unit/user_test.rb
Labels: in progress

#4309 Change to coveralls.wear!
  test/test_helper.rb
Labels: in progress

#4212 Add Outlook Reply By Email Feature
  app/models/comment.rb
  test/fixtures/drupal_users.yml
  test/fixtures/incoming_test_emails/outlook/final_parsed_comment.txt
  test/fixtures/incoming_test_emails/outlook/incoming_outlook_email.eml
  test/fixtures/incoming_test_emails/outlook/incoming_outlook_email.html
  test/fixtures/incoming_test_emails/outlook/readme.md
  test/fixtures/users.yml
  test/integration/incoming_mail_parsing_test/outlook_parsing_test.rb
Labels: ready

#4325 Fix profiles search display results
  app/views/search/profiles.html.erb
Labels: in progress

#4225 Link Login Modal to follow a post
  app/views/tag/blog.html.erb
Labels: in progress

#4338 Supportive tasks instead of GCI tasks
  README.md
Labels: ready

#4343 Add refactoring helper to application controller
  app/controllers/application_controller.rb
  app/views/users/profile.html.erb
Labels: in progress

#4256 Implement questions answered vs questions asked
  Gemfile
  Gemfile.lock
  app/controllers/questions_controller.rb
  app/helpers/questions_helper.rb
  app/views/questions/index.html.erb
  test/unit/helpers/questions_helper_test.rb
Labels: in progress

#4345 Removed redundant code from the edit view of user
  app/views/users/_edit_form.html.erb
Labels: ready

#4292 Node: latitude/longitude storage
  db/migrate/20181219043340_add_fields_to_node.rb
  db/schema.rb.example
Labels: ready

#4340 Multi Tag Subscription
  app/controllers/subscription_controller.rb
  config/routes.rb
Labels: review-me

#4387 Minor fix
  app/controllers/subscription_controller.rb
Labels: in progress

#4398 Login modal bug fix
  app/views/user_sessions/_new.html.erb
Labels: in progress

#4403 Fix(modal): Use new anchor class for ask question on wiki page
  app/views/grids/_notes.html.erb
Labels: in progress

#4404 Fix(modal): Use new anchor class for activity on wiki pages. Remove obsolete gridLinkModal.
  app/views/grids/_notes.html.erb
Labels: ready

#4407 Fix(Blurred Location Input): Only show blurred location modal
  app/views/locations/_modal.html.erb
  app/views/tag/_location.html.erb
Labels: ready

#4302 Date range selector for stats
  app/controllers/stats_controller.rb
  app/views/layouts/application.html.erb
  app/views/stats/range.html.erb
Labels: in progress

#4438 [WIP] Return_to for signup
  app/controllers/users_controller.rb
  app/views/users/_create_form.html.erb
  config/locales/controllers/users_controller/en.yml
Labels: in progress

#4451 Fix(Signup Modal): Link signup modal at questions-answers
  app/views/questions/_answers.html.erb
Labels: ready

#4455 Adapt requireLogin for signup
  app/views/questions/_answers.html.erb
  app/views/user_sessions/_new.html.erb
Labels: in progress
