Repository publiclab/plots2, pull requests merged in 2018-04, with the labels that each got.

#2430 Social media icons should link to latest entered username #2429
  app/models/user.rb
Labels: first-timers-only, ready

#2561 Infinite scroll of map and panning out of map boundaries . #2248
  app/assets/javascripts/application.js
  app/assets/javascripts/leaflet_helper.js
  app/views/map/_userLeaflet.html.erb
Labels: ready

#2578 tags not shown on search resolved
  app/controllers/tag_controller.rb
  test/functional/tag_controller_test.rb
Labels: ready

#2533 Upgrade to Rails 4.2
  Gemfile
  Gemfile.lock
  app/controllers/admin_controller.rb
  app/controllers/answer_like_controller.rb
  app/controllers/answers_controller.rb
  app/controllers/user_sessions_controller.rb
  app/controllers/users_controller.rb
  app/mailers/admin_mailer.rb
  app/mailers/comment_mailer.rb
  app/mailers/password_reset_mailer.rb
  app/mailers/subscription_mailer.rb
  app/mailers/welcome_mailer.rb
  app/models/answer.rb
  app/models/comment.rb
  app/models/drupal_content_type_map.rb
  app/models/node.rb
  app/models/spamaway.rb
  app/models/user.rb
  config/application.rb
  config/database.yml.example
  config/environments/production.rb
  config/environments/test.rb
  test/fixtures/drupal_content_type_map.yml
  test/functional/admin_controller_test.rb
  test/functional/editor_controller_test.rb
  test/functional/home_controller_test.rb
  test/functional/map_controller_test.rb
  test/functional/notes_controller_test.rb
  test/functional/tag_controller_test.rb
  test/functional/users_controller_test.rb
  test/functional/wiki_controller_test.rb
  test/integration/I18n_test.rb
  test/integration/node_insert_extras_test.rb
  test/integration/node_series_tag_test.rb
  test/integration/node_unique_views_test.rb
  test/test_helper.rb
  test/unit/admin_mailer_test.rb
  test/unit/answer_mailer_test.rb
  test/unit/comment_mailer_test.rb
  test/unit/subscription_mailer_test.rb
Labels: ready

#2585 [WIP] Adding Search bar to Maps . #2582
  app/views/layouts/application.html.erb
  app/views/map/_peopleLeaflet.html.erb
Labels: in-progress

#2417 Add spam button to dashboard page (Fixes #2412)
  app/views/dashboard/_node_meta.html.erb
Labels: in progress

#2600 render_map changes
  app/helpers/application_helper.rb
  app/views/sidebar/_related.html.erb
Labels: ready

#2609 Update _tags.html.erb to refine tags popup
  app/views/tag/_tags.html.erb
Labels: in progress

#2605 initial fix attempt for comment/answer markdown
  app/helpers/application_helper.rb
  app/models/answer.rb
  app/models/comment.rb
  app/views/dashboard/_node_comment.html.erb
  app/views/notes/_comment.html.erb
  app/views/questions/_answer.html.erb
  app/views/questions/_comment.html.erb
  app/views/tag/_tags.html.erb
  test/fixtures/drupal_content_type_map.yml
  test/functional/notes_controller_test.rb
  test/functional/questions_controller_test.rb
  test/unit/answer_test.rb
  test/unit/comment_test.rb
Labels: in progress

#2601 Changing the zoom level of the user marker in the search result
  app/views/map/_peopleLeaflet.html.erb
Labels: fto-candidate, ready

#2615 Comment creation with status = 1
  app/models/node.rb
  db/seeds.rb
Labels: ready

#2622 Hide "stale page" notice for locked pages
  app/views/wiki/show.html.erb
Labels: ready

#2612 Fixed #2602: group page map showing everybody problem fixed
  app/api/srch/search.rb
  app/controllers/users_controller.rb
  app/models/search_request.rb
  app/services/search_service.rb
  app/views/map/_peopleLeaflet.html.erb
  test/functional/restful_search_test.rb
  test/functional/search_api_test.rb
Labels: review-me

#2621 Add test for questions count on methods page
  app/models/node.rb
  app/views/notes/_notes.html.erb
  test/functional/wiki_controller_test.rb
Labels: in progress

#2630 Remove static text for text "feature" (issue #2629)
  app/views/notes/tools_places.html.erb
Labels: fto-candidate, ready

#2637 Hide comments from front page, inefficiently
  app/controllers/home_controller.rb
Labels: in progress

#2633 Spam flag changes
  app/views/dashboard/_node_meta.html.erb
  test/functional/home_controller_test.rb
Labels: ready

#2636 Changed buttons to the same size
  app/views/notes/_coauthored_notes.html.erb
Labels: fto-candidate, ready

#2648 test revision spam flows
  app/controllers/admin_controller.rb
  test/integration/revision_spam_test.rb
Labels: in progress

#2645 Updated functional test in tag_controller_test.rb to replace deprecated assert_tag with assert_select
  test/functional/tag_controller_test.rb
Labels: ready

#2619 Improved graphs on contributors/tags pages
  app/models/tag.rb
  app/views/tag/contributors.html.erb
Labels: ready

#2654 'old' reports url, fixes #824
  app/controllers/legacy_controller.rb
Labels: in progress

#2618 Add time ranges in tag_controller#show
  app/controllers/tag_controller.rb
  app/views/tag/show.html.erb
  config/routes.rb
  test/functional/tag_controller_test.rb
Labels: in progress

#2639 Added validation errors
  app/models/node.rb
Labels: review-me

#2658 Update legacy_controller.rb to fix redirect
  app/controllers/legacy_controller.rb
Labels: in progress

#2626 Update _notes.html.erb
  app/views/grids/_notes.html.erb
Labels: ready

#2670 Banned users with location tags appear on the /people map #2628
  app/services/search_service.rb
Labels: ready

#2673 Update revisions.html.erb
  app/views/wiki/revisions.html.erb
Labels: ready
