Repository publiclab/plots2, pull requests merged in 2018-03, with the labels that each got.

#2424 Update _header.html.erb
  app/views/layouts/_header.html.erb
Labels: in progress

#2415 Add larger image to profile page
  app/views/users/profile.html.erb
Labels: ready

#2434 Sign removed from comments
  app/views/notes/_comment.html.erb
Labels: ready

#2433 Mailer test when Barnstar tag added
  app/views/comment_mailer/notify_barnstar.html.erb
  test/unit/comment_mailer_test.rb
Labels: ready, review-me

#2409 Ensure "spam" profiles don't appear on People map
  app/controllers/users_controller.rb
Labels: ready

#2371 Home controller tests - test redirect and title
  test/functional/home_controller_test.rb
Labels: ready

#2296 added recent notes page
  app/controllers/notes_controller.rb
  app/views/dashboard/_header.html.erb
  app/views/notes/index.html.erb
  config/locales/controllers/notes_controller/de.yml
  config/locales/controllers/notes_controller/en.yml
  config/locales/views/notes/index/de.yml
  config/locales/views/notes/index/en.yml
  config/routes.rb
  test/functional/notes_controller_test.rb
Labels: ready

#2293 Profile page likes rendered on the same page
  app/controllers/users_controller.rb
  app/views/users/_likes.html.erb
  app/views/users/profile.html.erb
Labels: ready

#2259 Comment and sent email when co-author added
  app/controllers/tag_controller.rb
  app/mailers/comment_mailer.rb
  app/views/comment_mailer/notify_answer_author.html.erb
  app/views/comment_mailer/notify_coauthor.html.erb
  app/views/comment_mailer/notify_note_author.html.erb
  test/functional/tag_controller_test.rb
  test/unit/comment_mailer_test.rb
Labels: ready

#2448 Add methods to User model for verifying user roles
  app/models/user.rb
  test/unit/user_test.rb
Labels: review-me, testing

#2438 Minor refactor of Home controller 'activity'
  app/controllers/home_controller.rb
Labels: ready

#2395 Development script for quick and reliable setup
  bin/setup
Labels: ready

#2477 Fixes tag controller "suggested tags" action
  app/controllers/tag_controller.rb
Labels: ready

#2481 Updated application_controller.rb to fix moderation alert message
  app/controllers/application_controller.rb
  test/functional/notes_controller_test.rb
Labels: ready

#2435 Remove some redundant tests from Home controller
  test/functional/home_controller_test.rb
Labels: review-me, testing

#2297 remove extra dashboard route
  config/routes.rb
Labels: review-me

#2519 Solve bug in reset password
  app/models/user.rb
Labels: ready

#2508 Minor refactor of Users controller, using User's new methods to check…
  app/controllers/users_controller.rb
Labels: ready

#2507 Tidy app js in views/tag/index.html.erb
  app/views/tag/index.html.erb
Labels: ready

#2473 Tags should not be created when string has #____ in it
  app/models/revision.rb
  config/initializers/constants.rb
  test/fixtures/revisions.yml
  test/unit/revision_test.rb
Labels: ready

#2522 Refactor of Notes controller, using User's new methods to check …
  app/controllers/notes_controller.rb
Labels: ready

#2523 Rich Wiki
  app/controllers/wiki_controller.rb
  app/views/editor/wikiRich.html.erb
  test/functional/wiki_controller_test.rb
  test/integration/wiki_creation_test.rb
Labels: ready

#2526 Refactor Users controller - Add before filter for info, followed, following...
  app/controllers/users_controller.rb
Labels: ready

#2532 Refactor Wiki controller using User's new methods to check users' …
  app/controllers/wiki_controller.rb
Labels: ready

#2515 comment_controller.rb updated (Fixes #2399)
  app/controllers/comment_controller.rb
Labels: ready

#2531 Oauth routes, figaro and config/initializers file updates
  Gemfile
  app/views/users/_form.html.erb
  config/initializers/omniauth.rb
  config/routes.rb
Labels: ready

#2361 Added heat maps feature for profile
  app/assets/javascripts/users.js
  app/models/user.rb
  app/views/users/profile.html.erb
  test/unit/user_test.rb
Labels: in progress

#2536 Feature SkyTruth Alerts map as a layer in Leaflet profile map
  app/views/layouts/application.html.erb
  app/views/map/_userLeaflet.html.erb
Labels: ready

#2541 Wiki rich flash message removed from create
  app/controllers/wiki_controller.rb
Labels: ready

#2087 List people by profile tag at /people/TAGNAME
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/users/list.html.erb
  config/routes.rb
Labels: ready

#2548 Added redirect by page name feature to the redirect tag and a test for it.
  app/controllers/wiki_controller.rb
  test/functional/wiki_controller_test.rb
Labels: fto-candidate, in-progress

#2545 Modify edit in Users controller. Add functional tests for edit and …
  app/controllers/users_controller.rb
  test/functional/users_controller_test.rb
Labels: review-me
