Repository publiclab/plots2, pull requests merged in 2018-07, with the labels that each got.

#2954 change front page blog length
  app/controllers/home_controller.rb
Labels: in progress

#2959 Configuration settings for facebook provider
  config/initializers/omniauth.rb
Labels: ready

#2961 Omniauth hash for Twitter
  config/environments/test.rb
Labels: ready

#2960 Docker changes done for fb
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
Labels: ready

#2962 User Session Controller tests for twitter
  test/functional/user_sessions_controller_test.rb
Labels: ready

#2963 Integration tests for twitter
  test/integration/login_flow_test.rb
Labels: ready

#2965 Added fb test hash
  config/environments/test.rb
Labels: ready

#2966 User Session Controller tests for Facebook
  test/functional/user_sessions_controller_test.rb
Labels: ready

#2964 Integration tests for facebook
  test/integration/login_flow_test.rb
Labels: ready

#2927 Rails 5.2 upgrade
  Gemfile
  Gemfile.lock
  app/controllers/notes_controller.rb
  app/controllers/questions_controller.rb
Labels: ready, summer-of-code

#2973 Added routes for updating of comment
  config/routes.rb
  test/integration/routes_test.rb
Labels: in progress

#2772 mount sidekiq dashboard
  app/controllers/users_controller.rb
  app/jobs/digest_mail_job.rb
  app/models/user.rb
  app/views/users/profile.html.erb
  config/initializers/sidekiq.rb
  config/routes.rb
  config/schedule.rb
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-testing.yml
  containers/docker-compose-unstable.yml
  lib/admin_constraint.rb
  test/functional/users_controller_test.rb
Labels: review-me, summer-of-code

#2968 home page feature consolidation
  app/views/home/home.html.erb
  test/functional/home_controller_test.rb
Labels: in progress

#2978 fix docker compose stable dependency bug
  containers/docker-compose-stable.yml
Labels: in progress

#2976 Mailman needs secret_key_base env var, adding it!
  containers/docker-compose-production.yml
Labels: in progress

#2847 Implement API tagging location
  app/api/srch/search.rb
  app/services/search_service.rb
  test/functional/search_api_test.rb
Labels: review-me, summer-of-code

#2993 added font awsome facebook icon
  app/views/layouts/_header.html.erb
  app/views/user_sessions/new.html.erb
  app/views/users/edit.html.erb
  app/views/users/new.html.erb
Labels: ready

#3000 Remove duplicate environment variable.
  Makefile
  containers/docker-compose-production.yml
Labels: in progress

#3004 Delete en.yml
  config/locales/views/home/home/en.yml
Labels: in progress

#2984 Prep for rubocop ci
  .gitignore
  .rubocop.yml
  .rubocop_shopify_styleguide.yml
  .travis.yml
  Gemfile
  app/controllers/admin_controller.rb
  app/controllers/application_controller.rb
  app/controllers/comment_controller.rb
  app/controllers/home_controller.rb
  app/controllers/like_controller.rb
  app/controllers/map_controller.rb
  app/controllers/notes_controller.rb
  app/controllers/stats_controller.rb
  app/controllers/subscription_controller.rb
  app/controllers/tag_controller.rb
  app/controllers/user_sessions_controller.rb
  app/controllers/users_controller.rb
  app/controllers/wiki_controller.rb
  app/helpers/application_helper.rb
  app/mailers/subscription_mailer.rb
  app/models/answer.rb
  app/models/comment.rb
  app/models/concerns/node_shared.rb
  app/models/drupal_content_type_map.rb
  app/models/image.rb
  app/models/like.rb
  app/models/node.rb
  app/models/spamaway.rb
  app/models/tag.rb
  app/models/user.rb
  app/views/notes/rss.rss.builder
  app/views/tag/rss.rss.builder
  app/views/tag/rss_for_tagged_with_author.rss.builder
Labels: ready

#3015 Fix a bunch of offenses
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  app/api/srch/search.rb
  app/controllers/admin_controller.rb
  app/controllers/answers_controller.rb
  app/controllers/application_controller.rb
  app/controllers/comment_controller.rb
  app/controllers/home_controller.rb
  app/controllers/like_controller.rb
  app/controllers/map_controller.rb
  app/controllers/notes_controller.rb
  app/controllers/openid_controller.rb
  app/controllers/questions_controller.rb
  app/controllers/searches_controller.rb
  app/controllers/stats_controller.rb
  app/controllers/subscription_controller.rb
  app/controllers/tag_controller.rb
  app/controllers/user_sessions_controller.rb
  app/controllers/user_tags_controller.rb
  app/controllers/users_controller.rb
  app/controllers/wiki_controller.rb
  app/helpers/application_helper.rb
  app/helpers/comment_helper.rb
  app/mailers/answer_mailer.rb
  app/mailers/subscription_mailer.rb
  app/models/answer.rb
  app/models/answer_selection.rb
  app/models/application_record.rb
  app/models/comment.rb
  app/models/concerns/node_shared.rb
  app/models/doc_result.rb
  app/models/drupal_content_field_image_gallery.rb
  app/models/drupal_user.rb
  app/models/image.rb
  app/models/node.rb
  app/models/node_tag.rb
  app/models/revision.rb
  app/models/spamaway.rb
  app/models/tag.rb
  app/models/user.rb
  app/models/user_tag.rb
  app/services/search_service.rb
  app/services/typeahead_service.rb
  app/views/notes/rss.rss.builder
  app/views/tag/rss.rss.builder
  app/views/tag/rss_for_tagged_with_author.rss.builder
  app/views/users/rss.rss.builder
Labels: ready

#2982 Extended reply by email feature to reply to answer
  app/mailers/answer_mailer.rb
  app/mailers/comment_mailer.rb
  app/models/comment.rb
  app/views/comments/_comments.html.erb
  app/views/questions/_comment.html.erb
  test/unit/answer_mailer_test.rb
  test/unit/comment_mailer_test.rb
  test/unit/comment_test.rb
Labels: in progress, summer-of-code

#2983 Merge answer/user commenting interface
  app/assets/stylesheets/comments.css
  app/controllers/comment_controller.rb
  app/views/comment/create.js.erb
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  app/views/notes/_comment.html.erb
  app/views/questions/_answer.html.erb
  app/views/questions/_answers.html.erb
  app/views/questions/show.html.erb
  test/functional/comment_controller_test.rb
Labels: review-me

#2999 update likes with emoji_type: nil to emoji_type: ThumbsUp
  db/migrate/20180705203310_convert_nil_emoji_type_likes_to_thumbs_up.rb
  db/schema.rb.example
Labels: review-me, summer-of-code

#3031 Password changed
  app/models/user.rb
Labels: ready

#3025 Mailer for on-boarding newcomer
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/mailers/welcome_mailer.rb
  app/views/welcome_mailer/notify_newcomer.html.erb
  test/fixtures/nodes.yml
  test/fixtures/revisions.yml
  test/unit/welcome_mailer_test.rb
Labels: in progress, ready, summer-of-code

#3006 migration for changing status of comments
  db/migrate/20180707065151_change_status_of_comments.rb
  db/schema.rb.example
Labels: ready, summer-of-code

#2957 Spam comment moderation
  Dangerfile
  app/controllers/admin_controller.rb
  app/controllers/users_controller.rb
  app/views/notes/_comment.html.erb
  app/views/notes/_comments.html.erb
  config/routes.rb
  test/fixtures/comments.yml
  test/functional/admin_controller_test.rb
  test/functional/notes_controller_test.rb
Labels: ready

#3048 re-add upgrade comment button
  app/views/notes/_comment.html.erb
Labels: in progress

#3044 errors on signup page
  app/views/users/_form.html.erb
  app/views/users/new.html.erb
Labels: in progress

#3021 Swap the providers and email-password login
  app/views/user_sessions/new.html.erb
Labels: ready

#3039 Uid visible to admin and account holder
  app/views/tag/_tags.html.erb
  test/functional/users_controller_test.rb
Labels: ready, summer-of-code

#3052 Fallback email and welcome email with Oauth
  app/controllers/user_sessions_controller.rb
  app/views/welcome_mailer/notify_newcomer.html.erb
  test/fixtures/revisions.yml
  test/functional/users_controller_test.rb
  test/unit/welcome_mailer_test.rb
Labels: ready, summer-of-code

#3057 Add rake tmp:cache:clear to Makefile
  Makefile
Labels: in progress

#3058 Add link to smtp for sidekiq
  Makefile
Labels: in progress

#3020 Added remaining unit tests for #2933
  test/fixtures/incoming_test_emails/gmail/filtered_comment.txt
  test/fixtures/incoming_test_emails/gmail/final_parsed_comment.txt
  test/fixtures/incoming_test_emails/gmail/incoming_gmail_email.eml
  test/fixtures/incoming_test_emails/gmail/incoming_gmail_email.html
  test/fixtures/incoming_test_emails/gmail/readme.md
  test/fixtures/incoming_test_emails/gmail/trimmed_content.txt
  test/fixtures/incoming_test_emails/yahoo/final_parsed_comment.txt
  test/fixtures/incoming_test_emails/yahoo/incoming_yahoo_email.eml
  test/fixtures/incoming_test_emails/yahoo/incoming_yahoo_mail.html
  test/fixtures/incoming_test_emails/yahoo/readme.md
  test/unit/comment_test.rb
  test/unit/helpers/application_helper_test.rb
Labels: in progress, summer-of-code

#3067 fixed error on edit page fixes #3060
  app/views/users/_form.html.erb
  app/views/users/edit.html.erb
Labels: ready, summer-of-code

#3068 Add CodeClimate documentation
  CODECLIMATE.md
  doc/images/code_climate.png
  doc/images/code_climate_1.png
  doc/images/codeclimate_read_up.png
  doc/images/cognitive_complexity_example.png
Labels: in progress, rgsoc

#3065 comments tab in /spam
  app/controllers/admin_controller.rb
  app/views/admin/_comments.html.erb
  app/views/admin/spam.html.erb
  config/routes.rb
  test/functional/admin_controller_test.rb
Labels: ready, summer-of-code

#3084 Update image src in email HTML for absolute routing
  app/models/revision.rb
Labels: in progress

#3080 add functionality for daily digest emails
  app/jobs/digest_mail_job.rb
  app/models/user.rb
  app/models/user_tag.rb
  config/schedule.rb
Labels: in progress

#3079 Added mail parsing for other email domains using google mail service
  app/models/comment.rb
  test/fixtures/drupal_users.yml
  test/fixtures/users.yml
  test/functional/search_api_test.rb
  test/unit/comment_test.rb
Labels: in progress

#3071 Password made safer
  app/models/user.rb
Labels: ready, summer-of-code

#3074 Upgraded the authlogic gem in Gemfile
  Gemfile
  Gemfile.lock
Labels: in progress

#3066 Uid made unvisible to client
  app/views/tag/_tags.html.erb
Labels: ready, summer-of-code

#3072 Few modification to auth login
  app/controllers/user_sessions_controller.rb
Labels: ready

#3073 Code cleanup leftovers
  app/views/answers/create.js.erb
  app/views/comment/create.js.erb
  app/views/comments/_form.html.erb
  app/views/questions/_answer.html.erb
Labels: review-me

#3088 Openssl digest for #3086
  app/models/user.rb
Labels: in progress

#3045 Remove API Search endpoints duplication
  app/api/srch/search.rb
  app/api/srch/shared_params.rb
  app/services/execute_search.rb
  app/services/search_criteria.rb
  app/services/search_service.rb
  test/functional/search_api_test.rb
Labels: in progress

#2617 Last created blog post shown instead of last updated, fixes #2443
  app/models/tag.rb
Labels: in progress

#3085 Fix cops
  .rubocop_shopify_styleguide.yml
Labels: in progress

#3097 Update _header.html.erb and application.html.erb for Open Graph tags
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
Labels: in progress

#3107 Refactor typeahead service
  app/api/srch/shared_params.rb
  app/api/srch/typeahead.rb
  app/services/execute_typeahead.rb
  test/functional/search_api_test.rb
  test/functional/typeahead_api_test.rb
Labels: in progress, review-me, rgsoc, summer-of-code

#3098 Migrated Rusers
  db/migrate/20180719165651_add_password_checker_to_users.rb
  db/schema.rb.example
Labels: review-me

#2985 Configurable Email Settings
  app/controllers/users_controller.rb
  app/models/comment.rb
  app/models/user.rb
  app/models/user_tag.rb
  app/views/home/subscriptions.html.erb
  app/views/layouts/_header.html.erb
  app/views/users/settings.html.erb
  config/routes.rb
  test/fixtures/user_tags.yml
  test/functional/comment_controller_test.rb
Labels: feature, review-me, summer-of-code

#2925 [WIP] (please do not merge yet) Add autocompleting usernames with @ symbol #2913
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.css
  app/controllers/home_controller.rb
  app/models/tag.rb
  app/views/comments/_form.html.erb
  public/lib/emoji.js
Labels: in progress

#2877 Issue 2596 - adds a link to wiki/software-outreach to header dropdown menu
  app/views/layouts/_header.html.erb
Labels: in progress

#3129 Update _like.html.erb with compact styling
  app/views/like/_like.html.erb
Labels: in progress

#3103 Removed skytruth overlay layer from profile page .
  app/views/map/_userLeaflet.html.erb
Labels: in progress

#3131 deep links for notes
  app/assets/javascripts/notes.js
  app/views/notes/show.html.erb
Labels: in progress

#3119 Configurable email settings
  app/controllers/users_controller.rb
  app/models/concerns/comments_shared.rb
  app/models/node.rb
  app/views/users/settings.html.erb
  test/fixtures/comments.yml
  test/fixtures/user_tags.yml
  test/functional/comment_controller_test.rb
  test/functional/like_controller_test.rb
Labels: ready, summer-of-code

#3037 wiki controller file (If wiki page doesn't exist)
  app/controllers/wiki_controller.rb
  test/functional/wiki_controller_test.rb
Labels: ready

#2725 skipping tag notification if first time poster
  app/models/node.rb
  test/fixtures/tag_selections.yml
  test/fixtures/tags.yml
  test/functional/tag_controller_test.rb
Labels: ready

#3148 Update srch_scope.rb
  app/services/search_service.rb
  app/services/srch_scope.rb
Labels: in progress

#3157 set node image default of basic logo
  app/controllers/notes_controller.rb
  public/logo.png
  test/functional/notes_controller_test.rb
Labels: in progress

#3156 Profile page count
  app/models/drupal_user.rb
  app/views/notes/index.html.erb
  app/views/users/profile.html.erb
  config/locales/views/notes/index/en.yml
Labels: ready

#3160 fix admin mailer!
  app/models/node.rb
Labels: in progress

#3114 Add some docs info
  doc/API.md
  doc/DATA_MODEL.md
  doc/TESTING.md
Labels: review-me
