Repository publiclab/plots2, pull requests merged in 2018-10, with the labels that each got.

#3489 Fixed typos #3366
  app/controllers/user_sessions_controller.rb
  test/functional/user_sessions_controller_test.rb
Labels: ready

#3546 (Preview - Hide Preview) Toggle Text Added for Post Comments in Questions
  app/assets/javascripts/editor.js
  app/views/comments/_form.html.erb
Labels: ready

#3516 Updated the file to correct spelling (fixes #3512)
  config/locales/views/users/info/en.yml
Labels: ready

#3448 Update Readme.md
  README.md
Labels: ready

#3547 Outreachy added to Readme
  README.md
Labels: ready

#3562 Update subscription_mailer.rb w node IDs
  app/mailers/subscription_mailer.rb
  test/functional/like_controller_test.rb
  test/unit/subscription_mailer_test.rb
Labels: in progress

#3580 Map full screen support removed and Hash removes as well .
  app/views/map/_leaflet.html.erb
  app/views/map/_peopleLeaflet.html.erb
  app/views/map/_userLeaflet.html.erb
  app/views/map/index.html.erb
Labels: in progress

#3189 preserve new wiki page creation path but redirect others to /tag/___
  app/controllers/wiki_controller.rb
  app/views/tag/show/_header.html.erb
  app/views/wiki/edit.html.erb
  test/functional/wiki_controller_test.rb
  test/integration/public_pages_test.rb
Labels: in progress

#3610 Prototype of photo gallery
  app/views/notes/_responses.html.erb
Labels: in progress

#3612 add lots of power tags to advanced tagging menu
  app/views/tag/_advanced_tagging.html.erb
Labels: in progress

#3641 Update install_cloudnine.sh - Ruby version
  install_cloudnine.sh
Labels: ready

#3624 shifted "Fixes #[Add issue number here.]" at top of pull_request_template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready

#3623 Enhanced README.md
  README.md
Labels: ready

#3638 changed instructions in the email body
  app/views/answer_mailer/notify_answer_likers_author.html.erb
  app/views/answer_mailer/notify_question_author.html.erb
  app/views/comment_mailer/notify_answer_author.html.erb
  app/views/comment_mailer/notify_barnstar.html.erb
  app/views/comment_mailer/notify_callout.html.erb
  app/views/comment_mailer/notify_coauthor.html.erb
  app/views/comment_mailer/notify_note_author.html.erb
  app/views/comment_mailer/notify_tag_followers.html.erb
Labels: in-progress

#3614 Add explanatory text while searching by profiles
  app/views/search/profiles.html.erb
Labels: ready

#3650 Removed "schedule" statement from pull_request_template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready

#3647 Removed extra horizontal lines in the mobile views of the maps page
  app/views/map/_maps.html.erb
Labels: ready

#3651 Fix - 3644 Fix button colliding with the enter tag in the mobile view
  app/assets/stylesheets/wiki.css
Labels: ready

#3668 Issue#3611
  .github/config.yml
Labels: ready

#3599 Removed requested line and else statement
  app/views/notes/_notes.html.erb
Labels: ready

#3671 Remove space from bundle exec commands after the colon
  README.md
Labels: ready

#3672 Update notes_controller.rb #3669
  app/controllers/notes_controller.rb
Labels: ready

#3687 Update config.yml
  .github/config.yml
Labels: ready

#3702 Update blog.css
  app/assets/stylesheets/blog.css
Labels: first-timers-only, ready

#3710 update link icon
  app/views/questions/_answer.html.erb
Labels: ready

#3709 Made documentation name uppercase
  doc/OMNIAUTH.md
Labels: ready

#3708 Minor fixes
  README.md
Labels: ready

#3718 tag search: fixing results url
  app/views/search/tags.html.erb
Labels: review-me, search

#3722 added image-sequencer
  package.json
Labels: in progress

#3719 Search API: new endpoint /srch/nearbyPeople
  app/api/srch/search.rb
  app/services/execute_search.rb
  app/services/search_service.rb
Labels: search

#3664 Fix - 3660 - Added Space between Asking a Question And Exploring Projects Button
  app/assets/stylesheets/dashboard.css
Labels: ready

#3714 explanatory-text-for-search-tags
  app/views/search/tags.html.erb
Labels: ready

#3717 Enhanced readability of commands in Readme
  README.md
Labels: ready

#3715 Redundant line removed
  README.md
Labels: ready

#3724 Tag generated for questions
  app/views/notes/_comment.html.erb
Labels: ready

#3746 Fixed typo on target
  app/views/editor/rich.html.erb
Labels: ready

#3751 Remove store option from navbarr
  app/views/layouts/_header.html.erb
Labels: ready

#3750 Open Store in Navbar in a new tab
  app/views/layouts/_header.html.erb
Labels: ready

#3749 Add tag parent method
  app/controllers/tag_controller.rb
  app/views/tag/show.html.erb
  config/routes.rb
  test/functional/tag_controller_test.rb
Labels: in progress

#3759 Fix inconsistent footer width in edit profile page
  app/views/users/edit.html.erb
Labels: ready

#3773 Pop-up for link social media button (#3584)
  app/views/users/profile.html.erb
Labels: ready

#3765 Adding NearbyPeople to API documentation
  doc/API.md
Labels: review-me

#3805 Allow admins to update profiles
  app/controllers/users_controller.rb
  app/views/users/_form.html.erb
Labels: in progress

#3804 Update images_controller.rb with dataurl filename and test
  app/controllers/images_controller.rb
  test/functional/images_controller_test.rb
Labels: in progress

#3806 Refactors mail parse test to integration from unit
  test/integration/incoming_mail_parsing_test/gmail_parsing_test.rb
  test/unit/comment_test.rb
Labels: ready

#3837 Update background color of login page in mobile
  app/views/layouts/_header.html.erb
Labels: ready

#3830 Extra scrubbing of email quoted text
  app/models/comment.rb
  test/unit/comment_test.rb
Labels: in progress
