Repository publiclab/plots2, pull requests merged in 2018-05, with the labels that each got.

#2682 Add Draft Label to the research note if status = 3. Fixes #2678
  app/controllers/comment_controller.rb
  app/views/notes/show.html.erb
Labels: ready

#2674 Added Flag as Spam button to comments in notes section. Fixes #2657
  app/views/notes/_comment.html.erb
Labels: ready

#2706 Added whenever gem for easily writing and deploying cron jobs
  Dockerfile
  Gemfile
  README.md
  config/schedule.rb
Labels: summer-of-code

#2730 Update readme installation, fixes #2729
  README.md
Labels: fto-candidate, ready

#2666 Draft display on Dashboard
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/controllers/notes_controller.rb
  test/functional/notes_controller_test.rb
Labels: review-me

#2593 Track Dockerfiles accross instances.
  Dockerfile
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
Labels: in progress

#2715 Added Sample Cron Job to check working of Whenever Gem
  Dockerfile
  Makefile
  app/models/user.rb
  config/schedule.rb
  public/cron_log.log
Labels: summer-of-code

#2591 add like feature for comments
  app/controllers/comment_controller.rb
  app/models/comment.rb
  app/models/like.rb
  app/models/user.rb
  app/views/comment/like_comment.js.erb
  app/views/notes/_comment.html.erb
  config/routes.rb
  db/migrate/20180406080905_create_likes.rb
  db/schema.rb.example
  test/fixtures/likes.yml
  test/functional/comment_controller_test.rb
  test/models/like_test.rb
Labels: in progress

#2748 Update README testing section
  README.md
Labels: ready
