Repository publiclab/plots2, pull requests merged in 2018-08, with the labels that each got.

#3101 [WIP] Leaflet Environmental layers integration
  app/views/layouts/application.html.erb
  app/views/map/_peopleLeaflet.html.erb
  bower.json
Labels: review-me

#3169 re-add skylight gem
  Gemfile
Labels: in progress

#3166 Integrated leaflet-environmental-layers library to /maps .
  app/views/map/index.html.erb
Labels: in progress

#3138 Fixes for responding to html get request while adding comment to an answer
  app/controllers/comment_controller.rb
  app/views/comment/create.html.erb
Labels: in progress, ready

#3174 disable tag notifications for content older than 1 month
  app/models/node.rb
Labels: in progress

#3173 Version changed of LEL .
  bower.json
Labels: review-me

#3163 Link addition to email for marking comment as spam
  app/views/comment_mailer/notify.html.erb
Labels: ready

#3140 Email settings documentation
  app/controllers/application_controller.rb
  doc/EMAIL.md
Labels: documentation, review-me, summer-of-code

#3178 Fix for blank /questions page
  app/views/questions/index.html.erb
Labels: in progress

#3158 Notifications field added while creating users with omniauth
  app/controllers/user_sessions_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  db/migrate/20180801144533_add_password_checker_to_rusers_and_remove_password_checker_from_users.rb
  db/schema.rb.example
  doc/Omniauth.md
  test/unit/user_test.rb
Labels: ready

#3113 improve UI of digest email
  app/views/subscription_mailer/send_digest.html.erb
  test/mailers/previews/subscription_mailer_preview.rb
Labels: review-me, summer-of-code

#3185 Migration for changing default value to true in node_selection `following`
  db/migrate/20180802114514_change_default_in_node_selection.rb
  db/schema.rb.example
Labels: in progress

#3186 Default_markers added in maps page
  app/views/map/index.html.erb
Labels: in progress

#3181 Gitlab CI script
  .gitlab-ci.yml
Labels: ready

#3199 update semver marks on leaflet-environmental-layers and leaflet-blurred-location
  bower.json
Labels: in progress

#3197 Add test task to Makefile
  Makefile
Labels: ready

#3195 Promote comment to answer
  app/controllers/comment_controller.rb
  app/views/comment/make_answer.js.erb
  app/views/notes/_comment.html.erb
  app/views/questions/_answer.html.erb
Labels: ready

#3201 migration for changing following to true for all rows of NodeSelection
  db/migrate/20180804215454_change_following_column_to_true_existing_rows.rb
  db/schema.rb.example
Labels: ready

#3202 Gitlab move to official docker-in-docker
  .gitlab-ci.yml
Labels: in progress

#3214 FULL screen added and common JS function used in people map
  app/views/map/_peopleLeaflet.html.erb
Labels: in progress

#3206 Documentation of Draft Feature
  doc/DATA_MODEL.md
Labels: draft-feature, ready, summer-of-code

#3207 Adds user options to spam-like comments or messages.
  app/views/comment_mailer/notify_note_author.html.erb
Labels: ready

#3134 Improve textSearch_profiles result
  app/api/srch/search.rb
  app/api/srch/shared_params.rb
  app/models/user.rb
  app/services/execute_search.rb
  app/services/search_criteria.rb
  app/services/search_service.rb
  app/services/srch_scope.rb
  db/migrate/20120101000000_drupal_schema.rb
  db/migrate/20180804042601_add_full_text_index_on_username.rb
  db/schema.rb.example
  test/fixtures/drupal_users.yml
  test/fixtures/nodes.yml
  test/fixtures/revisions.yml
  test/fixtures/users.yml
  test/functional/notes_controller_test.rb
  test/functional/search_api_test.rb
  test/unit/node_test.rb
  test/unit/user_test.rb
Labels: ready

#3217 Improve peopleLocations endpoint: people_locations method
  app/services/execute_search.rb
  app/services/search_service.rb
  app/services/srch_scope.rb
  test/unit/helpers/search_helper_test.rb
Labels: in progress, rgsoc, summer-of-code

#3235 API Search profiles: adding parameter to search (only) by username
  app/api/srch/search.rb
  app/api/srch/shared_params.rb
  app/api/srch/typeahead.rb
  app/assets/javascripts/atwho_autocomplete.js
  app/models/user.rb
  app/services/search_criteria.rb
  app/services/search_service.rb
  app/services/srch_scope.rb
  doc/API.md
  test/fixtures/drupal_users.yml
  test/fixtures/nodes.yml
  test/fixtures/revisions.yml
  test/fixtures/users.yml
  test/functional/notes_controller_test.rb
  test/functional/search_api_test.rb
  test/unit/node_test.rb
Labels: API, review-me, rgsoc, summer-of-code

#3253 Upgrade to Ruby 2.4.4 (fixes #2824)
  .dockerignore
  .gitlab-ci.yml
  .travis.yml
  Dockerfile
  Gemfile
  Makefile
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-testing.yml
  containers/docker-compose-unstable.yml
Labels: in progress

#3242 Fix schema-rb-example file for SQLite
  db/schema.rb.example
Labels: fixes, ready

#3234 Added new graphs to main tag page
  app/views/tag/_graph.html.erb
Labels: in progress

#3257 Remove Typeahead Service
  app/api/srch/api.rb
  app/api/srch/search.rb
  app/api/srch/shared_params.rb
  app/api/srch/typeahead.rb
  app/assets/javascripts/restful_typeahead.js
  app/controllers/searches_controller.rb
  app/models/tag_list.rb
  app/models/tag_result.rb
  app/services/execute_typeahead.rb
  app/services/search_service.rb
  app/services/srch_scope.rb
  app/services/typeahead_service.rb
  doc/API.md
  test/functional/restful_search_test.rb
  test/functional/search_api_test.rb
  test/functional/typeahead_api_test.rb
  test/unit/tag_result_test.rb
  test/unit/typeahead_service_test.rb
Labels: in progress

#3266 Fix route url on typeahead script
  app/assets/javascripts/restful_typeahead.js
Labels: in progress

#3251 Add unit test to the SearchService class methods
  app/assets/javascripts/atwho_autocomplete.js
  test/functional/api/search_api_full_text_test.rb
  test/functional/api/search_api_test.rb
  test/unit/api/search_service_full_text_search_test.rb
  test/unit/api/search_service_test.rb
Labels: API, ready, rgsoc, summer-of-code

#3269 fix wiki tag pages
  app/controllers/tag_controller.rb
Labels: in progress

#3270 Upgrade grape version from 1.0.3 to 1.1.0
  Gemfile.lock
Labels: API

#3146 Updating testing documentation
  doc/TESTING.md
Labels: in progress

#3280 fix leaflet-blurred-location geocoding
  app/views/locations/_form.html.erb
Labels: in progress
