Repository publiclab/plots2, pull requests merged in 2019-11, with the labels that each got.

#6342 Fix recent questions on shadow page
  app/views/questions/_recent_questions_shadow.html.erb
  app/views/questions/index_shadow.html.erb
Labels: bug-fix, design

#6788 PL.editor shows map if lat,lon passed in URL.
  app/controllers/editor_controller.rb
  app/views/editor/rich.html.erb
  package.json
  yarn.lock
Labels: review-me

#6802 map API using common global variable.
  app/assets/javascripts/leaflet_helper.js
  app/models/concerns/node_shared.rb
  app/views/map/_inlineLeaflet.html.erb
  app/views/map/_plainInlineLeaflet.html.erb
Labels: ready
