Repository publiclab/plots2, pull requests merged in 2019-03, with the labels that each got.

#4894 Refactor user model
  app/controllers/application_controller.rb
  app/models/comment.rb
  app/models/revision.rb
  app/models/user.rb
  app/services/search_service.rb
  test/unit/node_test.rb
Labels: ready

#4901 Convert chars to unicode at spamaway
  config/locales/en.yml
Labels: Translation System

#4885 Remove useless variable assignment
  app/models/user.rb
Labels: ready

#4913 Made moderate buttons to appear on the same line
  app/views/dashboard/_node_moderate.html.erb
Labels: in progress

#4902 Clean up
  .rubocop.yml
  .rubocop_shopify_styleguide.yml
  .rubocop_todo.yml
  app/api/srch/search.rb
  app/controllers/admin_controller.rb
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/controllers/images_controller.rb
  app/controllers/map_controller.rb
  app/controllers/notes_controller.rb
  app/controllers/openid_controller.rb
  app/controllers/subscription_controller.rb
  app/controllers/tag_controller.rb
  app/controllers/user_tags_controller.rb
  app/controllers/users_controller.rb
  app/controllers/wiki_controller.rb
  app/helpers/application_helper.rb
  app/helpers/openid_helper.rb
  app/models/comment.rb
  app/models/concerns/node_shared.rb
  app/models/concerns/statistics.rb
  app/models/doc_list.rb
  app/models/drupal_content_type_map.rb
  app/models/image.rb
  app/models/node.rb
  app/models/revision.rb
  app/models/search_request.rb
  app/models/tag.rb
  app/models/tag_selection.rb
  app/models/user.rb
  app/models/user_tag.rb
  app/services/search_service.rb
  config/initializers/abstract_mysql2_adapter.rb
  config/schedule.rb
  db/migrate/20140429190219_consolidate_tags.rb
  db/migrate/20140507095348_add_path_to_drupal_node.rb
Labels: ready

#4786 Move verification link
  app/views/welcome_mailer/notify_newcomer.html.erb
Labels: ready

#3175 Added reply by tweet feature
  Gemfile
  Gemfile.lock
  app/models/comment.rb
  app/models/node.rb
  config/initializers/twitter_client.rb
  config/schedule.rb
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
  db/migrate/20180809125000_add_tweet_column_to_comment.rb
  db/schema.rb.example
  doc/reply_by_tweet.md
Labels: in progress, summer-of-code

#4787 Addition of Translation prompts
  app/helpers/application_helper.rb
  app/views/dashboard/dashboard.html.erb
  app/views/home/subscriptions.html.erb
  app/views/layouts/application.html.erb
  app/views/tag/blog.html.erb
Labels: Translation System, in progress

#4918 Clean up
  .rubocop_todo.yml
  app/controllers/openid_controller.rb
  app/controllers/subscription_controller.rb
  app/controllers/tag_controller.rb
  app/controllers/user_sessions_controller.rb
  app/controllers/users_controller.rb
  app/models/answer.rb
  app/models/comment.rb
  app/models/concerns/comments_shared.rb
  app/models/concerns/node_shared.rb
  app/models/node.rb
  app/models/tag.rb
  app/models/user.rb
  app/services/execute_search.rb
  app/services/search_service.rb
  app/views/dashboard/_node_meta.html.erb
  app/views/grids/_thumbnail.html.erb
  app/views/map/_maps.html.erb
  app/views/notes/_coauthored_notes.html.erb
  app/views/notes/_draft_notes.html.erb
  app/views/notes/_notes.html.erb
  app/views/notes/_tagged_notes.html.erb
  app/views/tag/blog.html.erb
  app/views/wiki/_header.html.erb
Labels: ready

#4985 Fix the distorted css in pill
  app/views/tag/_tags.html.erb
Labels: ready

#5007 link to main stats page on tag stats page
  app/views/tag/stats.html.erb
Labels: ready

#4984 Remove requirement for mysql2 adapter when mysql database is not in use
  config/initializers/abstract_mysql2_adapter.rb
Labels: review-me

#5003 Fix #4971 Make move back and front arrows responsive
  app/views/stats/_range.html.erb
Labels: ready

#5023 Check if node is present before acting on it
  app/controllers/notes_controller.rb
  app/mailers/subscription_mailer.rb
  app/models/user.rb
Labels: ready

#4923 Clean up 3
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/admin_controller.rb
  app/controllers/application_controller.rb
  app/controllers/notes_controller.rb
  app/controllers/openid_controller.rb
  app/controllers/search_controller.rb
  app/controllers/stats_controller.rb
  app/controllers/subscription_controller.rb
  app/controllers/tag_controller.rb
  app/controllers/user_sessions_controller.rb
  app/controllers/users_controller.rb
  app/models/comment.rb
  app/models/node.rb
  app/models/user.rb
  app/models/user_tag.rb
  app/services/search_service.rb
Labels: ready

#5028 Fix NoMethodError: undefined method +status+ for nil:NilClass
  .codeclimate.yml
  app/controllers/application_controller.rb
  app/controllers/notes_controller.rb
  app/controllers/wiki_controller.rb
  app/views/notes/show.html.erb
  test/functional/notes_controller_test.rb
Labels: ready

#5040 Check that node is not nil
  app/controllers/questions_controller.rb
Labels: ready

#5041 Fix number of args
  app/mailers/subscription_mailer.rb
  app/models/user.rb
Labels: ready

#5043 Make questions bar graph responsive
  app/views/stats/_range.html.erb
Labels: ready

#5052 This fixes ActionView::Template::Error
  app/views/search/_profiles_blank.html.erb
  app/views/search/_questions_blank.html.erb
  app/views/search/_tags_blank.html.erb
  app/views/search/_wikis_blank.html.erb
  app/views/search/all_content.html.erb
Labels: ready

#5057 Complete some Rubocop todo items
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/answers_controller.rb
  app/models/answer.rb
  test/functional/answers_controller_test.rb
Labels: ready

#5067 Check if user exists before sending method
  app/controllers/user_sessions_controller.rb
Labels: ready

#5069 Safe navigate on session value
  app/controllers/openid_controller.rb
Labels: ready

#5075 Remove inexistent method call on User model
  app/controllers/users_controller.rb
Labels: ready

#5082 The search bar is inline with pagination
  app/views/tag/index.html.erb
Labels: in progress

#5080 Improve pagination for mobile view
  app/assets/stylesheets/style.css
Labels: ready

#4852 Likes Fix (button mashing and initial negative likes)
  app/assets/javascripts/application.js
  app/assets/javascripts/comment.js
  app/assets/javascripts/like.js
  app/views/comments/like_comment.js.erb
  app/views/like/_like.html.erb
  app/views/notes/_notes.html.erb
  package.json
  spec/javascripts/comment_spec.js
  spec/javascripts/fixtures/unlike.html
  spec/javascripts/helpers/mock-ajax.js
  spec/javascripts/inline_grids_spec.js
  spec/javascripts/like_spec.js
  spec/javascripts/plots2_spec.js
  spec/javascripts/spec_helper.js
  yarn.lock
Labels: needs review

#5093 Improved Profile dropdown to add a Font awesome icon
  app/views/layouts/_header.html.erb
Labels: ready

#5121 Redesigning the search bar
  app/views/tag/index.html.erb
Labels: ready

#5138 Added tests for sorting nodes on tag page by likes and views DESC
  test/fixtures/nodes.yml
  test/functional/tag_controller_test.rb
Labels: ready

#5152 Align download as buttons on smaller screens
  app/views/stats/_range.html.erb
Labels: ready

#5060 Delete lines 6-8 on package.json related to Bower
  .travis.yml
  Dockerfile
  install_cloudnine.sh
  package.json
Labels: ready

#5159 Remove assets not present deprecation warning
  app/views/admin/assets.html.erb
Labels: ready

#4537 Reply to comment (merge comments + answers) feature
  .gitignore
  app/controllers/comment_controller.rb
  app/models/comment.rb
  app/views/comments/_form.html.erb
  app/views/comments/create.js.erb
  app/views/notes/_comment.html.erb
  app/views/notes/_comments.html.erb
  app/views/questions/show.html.erb
  db/migrate/20190105183720_add_col_to_comments.rb
  db/migrate/20190303180731_migrate_answers_to_comments.rb
  db/schema.rb.example
  test/fixtures/comments.yml
  test/functional/comment_controller_test.rb
  test/functional/notes_controller_test.rb
  test/functional/questions_controller_test.rb
  test/unit/node_test.rb
Labels: needs review

#5100 Dividing the tags page to make it two-column and add graph in second column
  app/views/tag/index.html.erb
Labels: ready

#5025 fix return_to anomaly
  app/controllers/user_sessions_controller.rb
Labels: ready

#5087 Added Correct form validation
  app/views/user_sessions/_form.html.erb
Labels: ready

#5070 Closer mirroring between main stats and tag stats
  app/controllers/tag_controller.rb
  app/models/tag.rb
  app/views/tag/_graph.html.erb
  app/views/tag/stats.html.erb
  test/unit/tag_test.rb
Labels: in progress

#5202 Allow visibility of password
  app/views/user_sessions/_form.html.erb
Labels: ready

#5195 added on hover effects to profile icon
  app/views/layouts/_header.html.erb
Labels: ready

#5196 Fixes broken links for sorting the table on tag wiki pages
  app/views/wiki/_wikis.html.erb
Labels: ready

#3818 Update blog post limit
  app/controllers/tag_controller.rb
Labels: ready

#5145 Blank tag issue resolved in subscription
  app/controllers/subscription_controller.rb
  app/views/home/subscriptions.html.erb
Labels: ready

#5110 Divide of the span into two between tabs
  app/views/sidebar/_dashboard.html.erb
Labels: ready

#5081 Fix missing styling on profile comments page
  app/assets/javascripts/users.js
  app/controllers/users_controller.rb
  app/views/users/profile.html.erb
  test/functional/users_controller_test.rb
Labels: review-me

#5238 fix minor error while creating comments
  app/controllers/comment_controller.rb
  app/models/comment.rb
  app/views/comments/create.js.erb
  app/views/notes/_comment.html.erb
  app/views/notes/_comments.html.erb
  app/views/questions/show.html.erb
  test/functional/comment_controller_test.rb
Labels: needs review

#5134 Added unit test to find email using twitter username
  test/unit/comment_test.rb
Labels: ready

#5254 Fixed broken links (#5049)
  app/views/like/_like.html.erb
Labels: ready

#5246 Fixing Multi Tag Subscription Button
  app/views/tag/_subscribe_button.html.erb
  app/views/tag/_tags_popover.html.erb
Labels: ready

#5282 Fix onhover scroll effect
  app/views/map/_peopleLeaflet.html.erb
Labels: ready

#5240 User icon added in the near the dashboard
  app/views/layouts/_header.html.erb
Labels: ready

#5242 add information to bot
  .github/config.yml
Labels: ready

#3306 Use js libs from container in testing
  .gitlab-ci.yml
  .travis.yml
  containers/docker-compose-testing.yml
Labels: ready

#4514 Drop DrupalUsers "users" table
  db/migrate/20190104000000_remove_drupal_users.rb
  db/schema.rb.example
Labels: in progress

#5160 Add instructions to install ruby version 2.4.4
  README.md
  doc/PREREQUISITES.md
Labels: ready

#4961 Update _notes.html.erb
  app/views/notes/_notes.html.erb
Labels: ready

#5299 Added Skylight link on error page issue#5296 [WIP]
  public/500.html
Labels: in progress

#5029 Make the hover drop downs in the navbar instead of click.
  app/assets/stylesheets/question.css
Labels: in progress
