Repository publiclab/plots2, pull requests merged in 2019-07, with the labels that each got.

#5967 Issue templates added
  .github/ISSUE_TEMPLATE/--bug-report.md
  .github/ISSUE_TEMPLATE/--feature-request.md
  .github/ISSUE_TEMPLATE/--first-timers-only.md
Labels: needs review

#5948 Individual Page: Add new redesigned cards and change the test
  app/views/notes/_notes.html.erb
  app/views/questions/_new_question.html.erb
  app/views/tag/show/_tab_content.html.erb
  test/functional/notes_controller_test.rb
Labels: outreachy, review-me, summer-of-code

#5925 Individual tagpage: Add dropdown to distinct btw info and add test
  app/views/tag/show/_nav_tabs.html.erb
  test/functional/tag_controller_test.rb
  test/system/tags_controller_test.rb
Labels: outreachy, ready, summer-of-code

#5982 Fix the height of notes title in card
  app/views/notes/_notes.html.erb
Labels: ready

#5972 Added User Room, UserNotificationRoom and Browser Notification for comment Addition
  app/assets/javascripts/channels/user.js
  app/assets/javascripts/channels/user_notification.js
  app/channels/user_channel.rb
  app/channels/user_notification_channel.rb
  app/models/comment.rb
Labels: gsoc, summer-of-code

#5999 Adds Gray Circle to Topic Card
  app/views/tag/_topicCard.html.erb
Labels: ready

#4439 Follow unfollow asynchronous requests
  app/controllers/relationships_controller.rb
  app/views/like/_like.html.erb
  app/views/relationships/create.js.erb
  app/views/relationships/destroy.js.erb
  app/views/users/profile.html.erb
  test/functional/relationships_controller_test.rb
Labels: needs review

#5985 Added Test For Action Cable Streams
  Gemfile
  test/action_cable/cable_test.rb
Labels: gsoc, summer-of-code

#6006 Align Topic Card Images
  app/views/tag/_topicCard.html.erb
Labels: ready

#6015 Change layout from 4 cards to 3 cards in notes page.
  app/views/notes/_notes.html.erb
Labels: ready

#6013 updated profile picture design to circle from sqaure
  app/views/users/profile.html.erb
Labels: ready

#6017 Changed notification permission prompt to be appea only when user is logged in
  app/assets/javascripts/application.js
  app/views/layouts/application.html.erb
  config/initializers/assets.rb
Labels: gsoc, summer-of-code

#6023 Fix Users to notify via notification on commenting
  app/models/comment.rb
  test/action_cable/integration/comment_notification_test.rb
Labels: gsoc, summer-of-code

#6036 Added User Channel Tests
  app/channels/user_channel.rb
  test/action_cable/unit/user_channel_test.rb
Labels: gsoc, summer-of-code, testing

#5995 sidebar individual tags page
  app/views/map/_peopleLeaflet.html.erb
  app/views/tag/show.html.erb
  app/views/tag/show/_header.html.erb
  app/views/tag/show/_related_tags.html.erb
  app/views/tag/show/_tab_content.html.erb
  app/views/tag/show/_user_controls.html.erb
Labels: ready

#6032 Added Action Cable Connection Unit Tests
  test/action_cable/unit/connection_test.rb
Labels: gsoc, summer-of-code, testing

#6025 Fixed Repeated word issue
  config/locales/en.yml
Labels: ready

#6034 Added Room Channel Tests
  app/channels/room_channel.rb
  test/action_cable/unit/room_channel_test.rb
Labels: gsoc, summer-of-code, testing

#6049 Fix size of profile picture and center align
  app/views/users/profile.html.erb
Labels: ready

#6056 Added style color blue
  app/assets/stylesheets/style.css
  test.sqlite-journal
Labels: ready

#6058 Fixed #6057
  app/views/tag/show/_header.html.erb
Labels: ready

#6038 Added Tests for User Notification Channel
  app/channels/user_notification_channel.rb
  test/action_cable/unit/user_notification_channel_test.rb
Labels: gsoc, summer-of-code, testing

#6069 updated CSS to address issue #5959
  app/assets/stylesheets/style.css
  app/views/dashboard/_activity.html.erb
Labels: ready

#5990 Building profile page as per new style guide
  app/views/map/_userLeaflet.html.erb
  app/views/tag/_profileCard.html.erb
  app/views/users/profile.html.erb
  test/functional/users_controller_test.rb
Labels: design, outreachy, review-me, summer-of-code

#6060 Add extra spaces
  app/views/tag/show/_header.html.erb
Labels: ready

#6011 Sidebar: Add toggle icons
  app/views/like/_like.html.erb
  app/views/notes/show.html.erb
  app/views/sidebar/_related.html.erb
  app/views/wiki/_header.html.erb
  test/integration/I18n_test.rb
Labels: design, outreachy, review-me, summer-of-code

#6075 Fixed Reply By Tweet Console Bug
  app/models/comment.rb
Labels: bug
