Repository publiclab/plots2, pull requests merged in 2019-05, with the labels that each got.

#5461 Simplify SQL queries of hidden_nids and coauthor_nids
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/models/node.rb
Labels: ready

#5169 html cards for people section
  app/views/map/_peopleLeaflet.html.erb
  app/views/users/list.html.erb
  test/integration/I18n_test.rb
  test/integration/public_pages_test.rb
Labels: in progress

#5659 Fix tag search results for maps
  app/views/tag/show/_tab_content.html.erb
  config/locales/en.yml
Labels: bug, ready

#5533 change deliver_now to deliver_later in answer_like_controller
  app/controllers/answer_like_controller.rb
Labels: in progress

#5738 Translation prompt improvement
  app/helpers/application_helper.rb
Labels: in progress

#5740 horizontal cards for people section
  app/views/users/list.html.erb
Labels: design, outreachy, review-me

#5730 Trim container build process.
  .travis.yml
  Dockerfile
  containers/docker-compose-testing.yml
  nodesource.gpg.key
  start.sh
Labels: ready

#5755 fix sidebar `Share your button` dropdown-menu position with bootstrap4
  app/views/sidebar/_dashboard.html.erb
Labels: design, upgarde-bootstrap4

#5756 Fix the editor-toolbox and image upload
  app/views/editor/_main_image.html.erb
  app/views/editor/_toolbar.html.erb
Labels: design, upgarde-bootstrap4

#5754 Fix map position to above in mobile responsiveness
  app/views/users/list.html.erb
Labels: design, outreachy, summer-of-code

#5766 fix cards for tags section
  app/views/tag/_topicCard.html.erb
Labels: design, review-me, summer-of-code

#5779 Tiny refactor
  .rubocop_shopify_styleguide.yml
  app/models/image.rb
  test/jobs/digest_mail_job_test.rb
  test/models/like_test.rb
  test/performance/browsing_test.rb
  test/unit/answer_mailer_test.rb
Labels: ready

#5765 Add tags on cards for people section
  app/views/users/list.html.erb
Labels: outreachy, review-me, summer-of-code

#5772 Fix margin for methods
  app/views/notes/_notes.html.erb
Labels: design, review-me

#5787 Add first section for shadow question page
  app/views/questions/index_shadow.html.erb
  config/routes.rb
Labels: design, outreachy, review-me, summer-of-code

#5696 fix #5691 add trigger: 'hover' on the script in subscribe button
  app/views/tag/_subscribe_button.html.erb
Labels: ready

#5767 Fix alignment in subscriptions
  app/views/home/subscriptions.html.erb
Labels: design, review-me, upgarde-bootstrap4

#5812 Remove translation helper from a button
  app/views/tag/blog.html.erb
Labels: ready

#5736 Newcomer welcome msg, emoji menu placement and img shape fix
  app/views/dashboard/dashboard.html.erb
  app/views/layouts/_header.html.erb
  app/views/notes/_comment.html.erb
  app/views/tag/_topicCard.html.erb
Labels: review-me

#5478 refactored questions/answered page
  app/controllers/questions_controller.rb
  app/views/dashboard/_node_question.html.erb
  app/views/questions/_questions.html.erb
  app/views/questions/index.html.erb
  test/functional/questions_controller_test.rb
  test/integration/I18n_test.rb
Labels: ready
