Repository publiclab/plots2, pull requests merged in 2019-04, with the labels that each got.

#5330 Corrected class name in migration file
  db/migrate/20190104000000_remove_drupal_users.rb
Labels: ready

#5362 Update Code of Conduct using https://publiclab.org/conduct
  CODE_OF_CONDUCT.md
Labels: ready

#5350 Breaking the word into next line
  app/views/notes/_comment.html.erb
Labels: ready

#5395 Exception / for textarea
  app/assets/javascripts/keybindings.js
Labels: ready

#5424 Cross-browser compatible styling for input[type=file]
  app/assets/stylesheets/application.css
  app/assets/stylesheets/cross_browser.css
Labels: CSS, cross-browser, enhancement, ready

#5026 Change cursor to pointer on hover
  app/views/dashboard/_wiki.html.erb
Labels: in progress

#5491 fix #5104 pluralization conditionals
  app/views/dashboard/_header.html.erb
  config/locales/en.yml
Labels: Ruby, ready

#5459 implemented tags/node_tags stats downloading
  app/controllers/stats_controller.rb
  app/models/node_tag.rb
  app/models/tag.rb
  app/views/stats/_range.html.erb
  config/routes.rb
  test/functional/stats_controller_test.rb
Labels: in progress

#3221 Added @mentioned notification feature for node
  app/controllers/notes_controller.rb
  app/mailers/node_mailer.rb
  app/models/node.rb
  app/views/node_mailer/notify_callout.html.erb
  test/functional/notes_controller_test.rb
  test/unit/node_test.rb
Labels: in progress

#5421 Extend #5372 BSTRP Check Box fix to all check boxes
  app/assets/stylesheets/application.css
  app/assets/stylesheets/btsp_checkbox_override.css.scss
  app/assets/stylesheets/dashboard.css
  app/assets/stylesheets/editor.css
  app/assets/stylesheets/login_modal.css.scss
  app/assets/stylesheets/style.css
  app/views/comments/_edit.html.erb
  app/views/dashboard/_activity.html.erb
  app/views/dashboard/dashboard.html.erb
  app/views/editor/rich.html.erb
  app/views/tag/_subscribe_button.html.erb
  app/views/tag/_tags_popover.html.erb
  app/views/user_sessions/_form.html.erb
  config/locales/en.yml
Labels: CSS, bug, enhancement, ready

#5483 Add search submit button in tags page
  app/views/tag/index.html.erb
Labels: ready

#5513 Remove tooltip on click from like button
  app/views/like/_like.html.erb
Labels: ready

#5479 Fixed position for back-to-top button #3387
  app/assets/stylesheets/style.css
Labels: ready

#5449 Blog's page read-more button implemented
  app/views/tag/blog2.html.erb
Labels: review-me

#5505 Changed unfollow btn to primary bootstrap color
  app/views/users/_unfollow.html.erb
Labels: ready

#5549 Upgrade to sassc-rails
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/btsp_checkbox_override.scss
  app/assets/stylesheets/location_tags.scss
  app/assets/stylesheets/login_modal.scss
  app/assets/stylesheets/user_tags.scss
Labels: dependencies, needs review

#5579 Added test for login case #5410
  test/integration/login_flow_test.rb
Labels: ready

#5560 Automate Multiple Tag Subscription
  app/controllers/user_sessions_controller.rb
  app/controllers/users_controller.rb
  test/integration/login_flow_test.rb
Labels: ready, review-me

#5472 Removal of OpenID Gateway page by Whitelisting PL apps
  app/controllers/openid_controller.rb
  app/views/openid/decide.html.erb
  test/integration/openid_test.rb
Labels: ready, review-me

#5559 Preserve `return_to` param when switching from /login to /signup
  app/views/user_sessions/_form.html.erb
Labels: ready, review-me

#5558 Return_to induced on the login page
  app/controllers/user_sessions_controller.rb
Labels: ready, review-me

#5566 Login subscription flow rectified
  app/controllers/user_sessions_controller.rb
  test/integration/login_flow_test.rb
Labels: ready, review-me

#5571 Data fetching from plots2 to MK and SWB
  app/controllers/openid_controller.rb
Labels: ready, review-me

#4386 Password Verification at Edit Profile Page
  app/controllers/users_controller.rb
  app/views/users/_edit_form.html.erb
  test/functional/users_controller_test.rb
Labels: ready

#5402 fix the bug of traceback error of server on webpage
  app/controllers/tag_controller.rb
  config/locales/en.yml
Labels: ready

#5561 Fix #5554 - Fixed typo in user dropdown in navbar.
  app/views/layouts/_header.html.erb
Labels: ready

#5518 Pages tagged with place get a full-width map across the top of the page (instead of in the sidebar)
  app/helpers/application_helper.rb
  app/models/node.rb
  app/views/layouts/application.html.erb
  app/views/map/_leaflet.html.erb
  app/views/sidebar/_related.html.erb
  test/fixtures/node_tags.yml
  test/fixtures/tags.yml
  test/system/place_tags_test.rb
Labels: review-me

#5603 Russian language added and all 7 new languages enabled
  config/application.rb
  config/locales/ru.yml
Labels: ready

#5621 Align /stats page content #5619 - index.html.erb
  app/views/stats/index.html.erb
Labels: needs review

#5586 OAuth route creation for MK
  app/controllers/legacy_controller.rb
  app/controllers/openid_controller.rb
  app/controllers/user_sessions_controller.rb
  config/routes.rb
  test/integration/openid_test.rb
Labels: needs review, ready, review-me

#5228 Add a deprecation notice for legacy editor
  app/controllers/editor_controller.rb
Labels: ready

#5602 Fix #5418: Fixed counter in comment section in notes
  app/assets/javascripts/comment.js
  app/views/comments/create.js.erb
Labels: ready

#5451 Changes deliver_now to deliver_later in answer_controlller
  app/controllers/answers_controller.rb
Labels: ready

#5567 New design for blog2 header
  app/views/tag/blog2.html.erb
Labels: in progress

#5544 Remove README.environment, move login credentials
  README.environment
  README.md
Labels: documentation, needs review
