Repository publiclab/plots2, pull requests merged in 2019-08, with the labels that each got.

#6082 Shift username from left column besides map to right below profile image #6071
  app/views/users/profile.html.erb
Labels: ready

#6099 Locking Chrome version
  Dockerfile
  Gemfile
  test/application_system_test_case.rb
  test/system/dashboard_test.rb
  test/system/post_test.rb
Labels: ready

#6079 Profile page: Add tags,edit option and ellipsis for extra info button with in sidebar
  app/views/users/profile.html.erb
Labels: design, outreachy, ready, summer-of-code

#6116 Success message on editing profile picture.
  app/views/users/_photo.html.erb
Labels: ready

#6098 Stop overflow of popup content
  app/views/like/_like.html.erb
Labels: ready

#6120 Add popular tags in first column of profile section
  app/views/users/profile.html.erb
Labels: design, outreachy, summer-of-code

#6148 Fix css syntax - !important #6146
  app/views/notes/_notes.html.erb
  app/views/tag/show/_header.html.erb
Labels: bug-fix, ready

#6149 Fix login modal width in tag page.
  app/views/layouts/_signupLoginModal.html.erb
  app/views/tag/show/_header.html.erb
Labels: bug-fix, ready

#6147 Fix sidebar button misplacement issue for Questions
  app/views/like/_like.html.erb
  app/views/questions/show.html.erb
  app/views/sidebar/_question.html.erb
Labels: bug-fix, review-me

#6145 Fix horizontal scroll in Individual tag page
  app/views/tag/show/_header.html.erb
Labels: bug-fix, ready

#6158 Added Service worker for notification on mobile phones
  app/assets/javascripts/channels/user_notification.js
  app/models/comment.rb
  public/sw.js
Labels: gsoc, summer-of-code

#6113 Simple Data Grapher: Integration + Research Note + Tests
  app/assets/javascripts/application.js
  app/assets/javascripts/simple-data-grapher.js
  app/controllers/csvfiles_controller.rb
  app/helpers/application_helper.rb
  app/helpers/csvfiles_helper.rb
  app/models/concerns/node_shared.rb
  app/models/csvfile.rb
  app/models/user.rb
  app/views/csvfiles/new.html.erb
  app/views/csvfiles/user_files.html.erb
  app/views/grids/_simple-data-grapher.html.erb
  config/initializers/assets.rb
  config/routes.rb
  db/migrate/20190708141605_create_csvfiles.rb
  db/migrate/20190708141804_add_csvfile_to_rusers.rb
  db/migrate/20190728135035_add_graphobject_to_csvfiles.rb
  db/schema.rb.example
  package.json
  test/fixtures/csvfiles.yml
  test/functional/csvfiles_controller_test.rb
  test/system/csvfiles_controllers_test.rb
  yarn.lock
Labels: gsoc, review-me, summer-of-code

#6144 Draft access reset
  app/controllers/application_controller.rb
  app/controllers/notes_controller.rb
  app/models/node.rb
  test/functional/notes_controller_test.rb
Labels: ready

#6192 Changing column type in Csvfiles
  db/migrate/20190822192847_change_column_types_to_text_csvfiles.rb
  db/schema.rb.example
Labels: ready

#6030 Action cable integration tests for browser notification while posting comments
  app/controllers/comment_controller.rb
  test/action_cable/integration/comment_notification_test.rb
  test/channels/room_channel_test.rb
  test/fixtures/comments.yml
  test/fixtures/user_tags.yml
  test/functional/notes_controller_test.rb
  test/unit/node_test.rb
  test/unit/tag_test.rb
Labels: gsoc, summer-of-code, testing

#6224 On Profile pages, have the profile picture and bio info stay on top when screen width decreases
  app/views/users/profile.html.erb
Labels: design, feature, review-me
