Repository publiclab/plots2, pull requests merged in 2019-06, with the labels that each got.

#5815 Un-necessary prompts removed from subscriptions page
  app/views/home/subscriptions.html.erb
  app/views/tag/blog.html.erb
Labels: ready

#5835 Change edit post alert message in _like.html.erb
  app/views/like/_like.html.erb
Labels: ready

#5496 remove answer notification code
  app/controllers/answer_like_controller.rb
  app/controllers/answers_controller.rb
  app/mailers/answer_mailer.rb
  app/models/answer.rb
  test/functional/answers_controller_test.rb
  test/unit/answer_mailer_test.rb
Labels: ready

#5836 Activerecord and some more standard translations added
  config/locales/en.yml
Labels: needs review

#5851 Side vertical nav tab and dropdown menu for search by results
  app/helpers/search_helper.rb
  app/views/search/_nav.html.erb
  app/views/search/all_content.html.erb
  app/views/search/notes.html.erb
  app/views/search/places.html.erb
  app/views/search/profiles.html.erb
  app/views/search/questions.html.erb
  app/views/search/wikis.html.erb
Labels: outreachy, review-me, summer-of-code

#5849 UI fix - tabs on questions page
  app/views/questions/index.html.erb
Labels: needs review

#5858 Fix overflow of tags in people section
  app/views/users/list.html.erb
Labels: outreachy, review-me, summer-of-code

#5859 temp Fix for popover overflow with ellipsis
  app/views/like/_like.html.erb
  app/views/tag/_tags.html.erb
Labels: bug, design, ready

#5596 Show some info instead of empty table
  app/views/subscriptions/digest.html.erb
  app/views/wiki/_wikis.html.erb
Labels: in progress

#5888 Delete README_FOR_APP
  doc/README_FOR_APP
Labels: documentation, needs review

#5854 Fix profile page subtabs for authored, co-authored and drafts
  app/views/users/profile.html.erb
Labels: ready

#5861 Add featured question section to shadow question page
  app/controllers/questions_controller.rb
  app/views/dashboard/_question_node_meta.html.erb
  app/views/questions/_questions_shadow.html.erb
  app/views/questions/index_shadow.html.erb
  config/routes.rb
  test/system/screenshots_test.rb
Labels: design, outreachy, review-me, summer-of-code

#5515 CSS fixed
  app/views/users/profile.html.erb
Labels: needs review

#5856 Fix the question form and add test
  app/assets/stylesheets/wiki.css
  app/views/editor/questionRich.html.erb
  test/system/post_question_test.rb
Labels: design, review-me

#5903 Individual tagpage: Fix absolute wiki image position and add followers to topic
  app/views/tag/show.html.erb
  app/views/tag/show/_header.html.erb
Labels: design, outreachy, ready, summer-of-code

#5847 Adding unstable documentation
  doc/TESTING.md
Labels: ready

#5744 Basic Setup of Action Cable
  app/assets/javascripts/application.js
  app/assets/javascripts/cable.js
  app/assets/javascripts/channels/room.js
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/channels/room_channel.rb
  app/controllers/application_controller.rb
  app/views/layouts/application.html.erb
  config/cable.yml
  config/environments/production.rb
  config/routes.rb
Labels: gsoc, review-me, summer-of-code

#5522 Recently used location in LBL modal .
  app/models/node.rb
  app/models/user.rb
  app/views/locations/_form.html.erb
  test/system/screenshots_test.rb
Labels: review-me
