Repository publiclab/plots2, pull requests merged in 2019-02, with the labels that each got.

#4511 Simplify the questions page
  app/views/dashboard/_flag_list.html.erb
  app/views/dashboard/_node_meta.html.erb
  app/views/questions/_questions.html.erb
  test/functional/home_controller_test.rb
Labels: in progress

#4763 Caching on heavily-used API calls: srch/api/profiles
  Gemfile
  app/api/srch/search.rb
Labels: UI/API improvements

#4718 Create a Guidelines page for check-in workflow
  README.md
  doc/CHECKINS.md
Labels: ready

#3723 Upgrade packages sources repositories
  Dockerfile
Labels: ready

#4769 New language locales added
  config/locales/ar.yml
  config/locales/es.yml
  config/locales/hi-IN.yml
  config/locales/it.yml
  config/locales/ko.yml
  config/locales/pt-BR.yml
Labels: Translation System

#4612 Removed Extra Space after 'Share'
  app/views/editor/rich.html.erb
Labels: ready

#4850 Inline map changes
  app/views/map/_leaflet.html.erb
  app/views/map/_peopleLeaflet.html.erb
Labels: in-progress

#4863 URL to emoji images corrected
  app/helpers/application_helper.rb
Labels: ready

#4841 Set a typeahead delay to prevent overloading server
  app/assets/javascripts/post.js
Labels: priority, ready

#4867 Remove newline to show FB and Twitter buttons on same line #4821
  app/assets/stylesheets/dashboard.css
  app/views/sidebar/_dashboard.html.erb
Labels: ready

#4835 Update _replication.html.erb
  app/views/tag/_replication.html.erb
Labels: in progress
