Repository publiclab/plots2, pull requests merged in 2019-09, with the labels that each got.

#6227 Fix change on hover and other bug-fix
  app/views/users/profile.html.erb
Labels: bug-fix, design, review-me

#6216 fix: Rename tag in profile page.
  app/views/users/profile.html.erb
Labels: bug-fix, ready

#6235 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: ready

#6103 Fix Subscribe tag and subscribe related tag mismatch working add post option when subscribed
  app/views/tag/_dropdown_subscribe.html.erb
  app/views/tag/show.html.erb
  app/views/tag/show/_user_controls.html.erb
Labels: outreachy, review-me, summer-of-code

#6256 Add validation for username,password,email etc
  app/assets/javascripts/application.js
  app/assets/javascripts/validation.js
  app/views/users/_create_form.html.erb
  app/views/users/_edit_form.html.erb
  package.json
  yarn.lock
Labels: JavaScript, design, review-me

#6255 Make profile user links more prominent
  app/views/users/profile.html.erb
Labels: design, review-me

#6292 Remove username from dashboard welcome message
  app/views/dashboard/_header.html.erb
Labels: ready
