Repository publiclab/plots2, pull requests merged in 2019-01, with the labels that each got.

#4488 Disabling Paste in all user authenticaiton forms(#4487)
  app/views/user_sessions/_new.html.erb
  app/views/user_sessions/new.html.erb
  app/views/users/_create_form.html.erb
  app/views/users/_edit_form.html.erb
Labels: in progress

#4489 removed ambiguous behaviour of 'Add one now' on local server
  app/views/tag/show/_header.html.erb
Labels: in progress

#3803 removed various libs: openid, solr
  app/models/user.rb
  config/application.rb
  config/initializers/authlogic_openid.rb
  lib/authlogic_openid/CHANGELOG.rdoc
  lib/authlogic_openid/MIT-LICENSE
  lib/authlogic_openid/Manifest.txt.old
  lib/authlogic_openid/README.rdoc
  lib/authlogic_openid/Rakefile.old
  lib/authlogic_openid/authlogic_openid.rb
  lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb
  lib/authlogic_openid/authlogic_openid/session.rb
  lib/authlogic_openid/authlogic_openid/version.rb
  lib/open_id_authentication/CHANGELOG
  lib/open_id_authentication/README
  lib/open_id_authentication/open_id_authentication.rb
Labels: in progress

#4390 Adding functional test
  test/fixtures/tags.yml
  test/functional/subscription_controller_test.rb
Labels: review-me

#4354 Fix for RSS missing rel="self" attribute
  app/views/tag/rss.rss.builder
Labels: ready

#4128 Change nearby nodes logic
  app/api/srch/search.rb
  app/api/srch/shared_params.rb
  app/models/search_request.rb
  app/services/execute_search.rb
  app/services/search_criteria.rb
  app/services/search_service.rb
  test/functional/api/search_api_test.rb
  test/unit/api/search_service_test.rb
Labels: review-me

#4492 Fix signup link at /login (#4457)
  app/views/user_sessions/_new.html.erb
  config/locales/views/user_sessions/new/en.yml
Labels: ready

#4513 Update home_controller.rb with cleanup
  app/controllers/home_controller.rb
Labels: in progress

#4379 Adding lat/lon values into node table
  app/models/node.rb
  test/unit/node_coordinates_test.rb
Labels: review-me

#4498 LEL New layers added .
  app/assets/javascripts/leaflet_helper.js
  app/views/map/_leaflet.html.erb
  app/views/map/_mapDependencies.html.erb
  app/views/map/_peopleLeaflet.html.erb
  app/views/map/_userLeaflet.html.erb
  app/views/map/index.html.erb
  package.json
Labels: ready

#4510 Dashboard sidebar code refactored
  app/views/dashboard/_header.html.erb
  app/views/dashboard/dashboard.html.erb
  app/views/sidebar/_dashboard.html.erb
Labels: review-me

#4516 Change nearby nodes logic (/api/srch/nearbyPeople)
  app/api/srch/search.rb
  app/services/execute_search.rb
  app/services/search_service.rb
  test/functional/api/search_api_test.rb
Labels: UI/API improvements, ready

#4300 Refactor Stats Controller
  app/controllers/stats_controller.rb
  app/models/node.rb
  app/models/revision.rb
  app/models/user.rb
Labels: in progress

#4497 Sharing of URL using hash LEL .
  app/assets/javascripts/leaflet_helper.js
  app/views/map/_leaflet.html.erb
  app/views/map/_peopleLeaflet.html.erb
  app/views/map/_userLeaflet.html.erb
  package.json
Labels: ready, review-me

#4462 Fixes #4422 login modal not working at /profile page
  app/views/users/_token.html.erb
  app/views/users/profile.html.erb
Labels: in progress

#4470 Comment listing on dashboard
  app/controllers/home_controller.rb
Labels: in progress

#4523 attempted fix for digests
  app/controllers/users_controller.rb
  app/models/user.rb
  app/models/user_tag.rb
  test/functional/users_controller_test.rb
  test/unit/user_tag_test.rb
Labels: in progress

#4544 Use of common functions at /maps .
  app/views/map/index.html.erb
Labels: ready, review-me

#4531 Using new API in maps .
  app/views/map/_peopleLeaflet.html.erb
Labels: ready, review-me

#4546 Moderated comment view for different users
  app/models/node.rb
  app/views/notes/_comment.html.erb
  app/views/notes/_comments.html.erb
  app/views/questions/show.html.erb
Labels: ready

#4464 Link login modal to follow a post
  app/views/like/_like.html.erb
Labels: in progress

#4545 removed the pseudo login button
  app/views/layouts/_header.html.erb
Labels: ready

#4435 Move stats from user model to a concern
  app/models/concerns/statistics.rb
  app/models/user.rb
  test/unit/statistics_test.rb
  test/unit/user_test.rb
Labels: in progress

#4564 Fixing “last active” column on /people
  app/controllers/users_controller.rb
Labels: UI/API improvements, review-me

#4571 added unit tests for sort by follower count
  test/unit/tag_test.rb
Labels: ready

#4458 user col removed from comments section in profile
  app/views/comments/_comments.html.erb
Labels: ready

#4579 LBL version updated
  package.json
Labels: ready, review-me

#4563 Implement Access token modal like Link social modal
  app/views/users/_token.html.erb
  app/views/users/profile.html.erb
Labels: in-progress

#4389 removed top margin to align buttons in mobile devices
  app/assets/stylesheets/wiki.css
  app/views/home/subscriptions.html.erb
Labels: in progress

#4584 Adding new locales "de.yml" and "zh-CN.yml"
  config/locales/de.yml
  config/locales/zh-CN.yml
Labels: ready

#4588 Spam revisions page fixed
  app/models/node.rb
  app/views/admin/_revisions.html.erb
Labels: in progress, priority

#4586 Updating API documentation
  app/api/srch/search.rb
  doc/API.md
Labels: UI/API improvements, ready

#4596 simplify save methods
  app/controllers/admin_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  test/functional/users_controller_test.rb
  test/unit/user_test.rb
Labels: in progress

#4576 Docs for `requireLogin`
  doc/LOGIN_SYSTEMS.md
Labels: review-me

#4597 [WIP] Adding sorting and ordering options to nearby people/nodes
  app/api/srch/search.rb
  app/api/srch/shared_params.rb
  app/services/execute_search.rb
  app/services/search_service.rb
  doc/API.md
  test/functional/api/search_api_test.rb
Labels: UI/API improvements, review-me

#4599 Username not editable in database
  app/models/user.rb
  test/unit/user_test.rb
Labels: in-progress

#4555 Multi tag subscription button
  app/views/tag/_subscribe_button.html.erb
  app/views/tag/_tagging.html.erb
  app/views/tag/_tags_popover.html.erb
Labels: in progress

#4605 reduced login redundancy
  app/views/layouts/_header.html.erb
  app/views/user_sessions/_new.html.erb
  app/views/user_sessions/new.html.erb
Labels: ready, review-me

#4538 Fixes #4311 optional profile picture at sign up
  app/views/users/_create_form.html.erb
Labels: ready, review-me

#4621 Test correction for PR #4599 which is failing travis builds
  test/unit/user_test.rb
Labels: priority

#4628 Added dependencies of Spinners in LBL .
  app/views/locations/_form.html.erb
Labels: review-me

#4633 LBL Slider added and spinner working (during auto-locate me !) .
  app/views/layouts/application.html.erb
  app/views/locations/_form.html.erb
Labels: review-me

#4572 UI fixes for range pages and stats page
  app/assets/stylesheets/style.css
  app/helpers/application_helper.rb
  app/views/stats/_stats_nav.html.erb
  app/views/stats/index.html.erb
  app/views/stats/range.html.erb
  config/locales/en.yml
Labels: in progress

#4600 Facebook share button added
  app/views/home/_social.html.erb
Labels: ready

#4615 Added breaklines in <a href> tag line 62.
  app/views/questions/_answer.html.erb
Labels: in progress

#4652 adjust last updated label in /people template
  app/views/users/list.html.erb
Labels: UI/API improvements, review-me

#4664 Refactoring `tagNearbyNodes()` API method
  app/services/search_service.rb
  test/fixtures/nodes.yml
  test/functional/api/search_api_test.rb
  test/unit/api/search_service_test.rb
Labels: UI/API improvements, review-me

#4655 [WIP] Adding user.watching_location() method
  app/models/user.rb
  test/fixtures/tag_selections.yml
  test/fixtures/tags.yml
  test/unit/subscription_location_test.rb
Labels: UI/API improvements, review-me

#4703 Adding `field` option to `/api/srch/nearbyPeople`
  app/api/srch/search.rb
  app/services/execute_search.rb
  app/services/search_service.rb
  doc/API.md
  test/unit/api/search_service_test.rb
Labels: UI/API improvements, review-me

#4709 removing `/api/srch/peoplelocations` endpoint and adding tests to `/api/srch/nearbyPeople`
  app/api/srch/search.rb
  app/services/execute_search.rb
  app/services/search_service.rb
  doc/API.md
  test/fixtures/tag_selections.yml
  test/functional/api/search_api_test.rb
  test/unit/api/search_service_test.rb
  test/unit/node_test.rb
Labels: UI/API improvements, review-me

#4710 Fix aspect ratio
  app/assets/stylesheets/style.css
  app/views/grids/_thumbnail.html.erb
Labels: review-me

#4733 Removing spams from taglocations results
  app/services/search_service.rb
Labels: UI/API improvements
