Repository publiclab/plots2, pull requests merged in 2020-12, with the labels that each got.

#8801 [Comment Editor #8775] System Test: Synchronous Comment from Question Page via JS + URL
  test/fixtures/node_tags.yml
  test/fixtures/nodes.yml
  test/fixtures/revisions.yml
  test/fixtures/tags.yml
  test/system/comment_test.rb
  test/unit/node_test.rb
Labels: testing

#8809 [Comment Editor] New Test: Comment on Notes with addComment Script
  test/fixtures/nodes.yml
  test/fixtures/revisions.yml
  test/functional/notes_controller_test.rb
  test/system/comment_test.rb
  test/unit/node_test.rb
Labels: readytomerge, testing

#8845 [Outreachy Comment Editor] New Test: Respond to Question Comment
  test/fixtures/comments.yml
  test/system/comment_test.rb
Labels: outreachy, testing

#8844 [Outreachy Comment Editor] New Test: Respond to Note Comment
  test/fixtures/comments.yml
  test/system/comment_test.rb
Labels: outreachy, testing

#8851 [Outreachy Comment Editor] New test: Post comment on question, then respond to it
  test/system/comment_test.rb
Labels: outreachy, testing

#8800 [Outreachy] Add All Posts Route /notes
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/controllers/notes_controller.rb
  app/models/node.rb
  app/views/notes/index.html.erb
  app/views/users/rss.rss.builder
  test/fixtures/node_tags.yml
  test/fixtures/nodes.yml
  test/fixtures/revisions.yml
  test/fixtures/tags.yml
  test/functional/notes_controller_test.rb
  test/integration/I18n_test.rb
  test/unit/node_test.rb
Labels: outreachy

#8848 [Outreachy] All Posts Design
  app/controllers/notes_controller.rb
  app/views/notes/_sidebar.html.erb
  app/views/notes/index.html.erb
  config/locales/en.yml
  test/fixtures/revisions.yml
Labels: outreachy

#8875 Filter Banned Users from User Reactions (Fixes #8618)
  app/controllers/comment_controller.rb
  app/models/comment.rb
  app/views/comments/like_comment.js.erb
  app/views/notes/_comment.html.erb
  test/unit/comment_test.rb
Labels: outreachy

#8886 [Outreachy] Dashboard Redesign URL
  app/controllers/home_controller.rb
  app/views/dashboard/dashboard_v2.html.erb
  config/locales/en.yml
  config/routes.rb
  test/functional/home_controller_test.rb
  test/unit/node_test.rb
  test/unit/user_test.rb
Labels: outreachy
