Repository publiclab/plots2, pull requests merged in 2020-01, with the labels that each got.

#5954 Remove coveralls, add codecov
  .codecov.yml
  .simplecov
  .travis.yml
  Gemfile
  Gemfile.lock
  Rakefile
  app/assets/stylesheets/blog.css
  test/test_helper.rb
Labels: in progress

#7104 Vertically aligned the menu icon for medium-sized screens
  app/views/layouts/_header.html.erb
Labels: ready

#7113 Fix OAuth redirection to previous url after LOGIN
  app/controllers/application_controller.rb
  app/views/layouts/_social_icons.html.erb
  test/functional/admin_controller_test.rb
  test/functional/csvfiles_controller_test.rb
  test/functional/editor_controller_test.rb
  test/functional/notes_controller_test.rb
  test/functional/subscription_controller_test.rb
  test/functional/tag_controller_test.rb
  test/functional/user_sessions_controller_test.rb
  test/functional/users_controller_test.rb
  test/functional/wiki_controller_test.rb
Labels: gci-candidate, hard

#7072 Add flash for logging in with banned users
  app/controllers/user_sessions_controller.rb
  test/functional/user_sessions_controller_test.rb
Labels: gci-candidate, hard

#7225 FIX: redirect to previous page when subscribing to multiple tags
  app/controllers/subscription_controller.rb
  app/views/tag/_tags_popover.html.erb
  test/functional/subscription_controller_test.rb
Labels: gci-candidate, medium

#7247 Added tests for Mapknitter openid login
  test/integration/openid_test.rb
Labels: gci-candidate, medium, reserved-for-gci

#7292 FIX: messages when logging in without password for oauth
  app/controllers/user_sessions_controller.rb
  test/functional/user_sessions_controller_test.rb
Labels: gci-candidate, medium, reserved-for-gci

#7336 Improved installation instructions
  README.md
Labels: ready
