Repository publiclab/plots2, pull requests merged in 2020-10, with the labels that each got.

#7542 empty wiki table header
  app/views/tag/show/_tab_content.html.erb
Labels: in-progress

#6109 Add automated-redeploy Make task
  Makefile
Labels: ready

#6050 Add all time stats option filter
  app/controllers/stats_controller.rb
  app/views/stats/index.html.erb
Labels: in-progress

#8673 Delete GCI_MENTOR_GUIDELINES.md
  doc/GCI_MENTOR_GUIDELINES.md
Labels: documentation, review-me
