Repository publiclab/plots2, pull requests merged in 2021-01, with the labels that each got.

#8927 Feature: Add Unique HTML IDs to .dropzones, #fileinputs
  app/helpers/application_helper.rb
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  app/views/editor/_editor.html.erb
  app/views/editor/_toolbar.html.erb
  app/views/notes/_comment.html.erb
  app/views/notes/_comments.html.erb
  app/views/notes/_responses.html.erb
  app/views/questions/show.html.erb
  test/system/comment_test.rb
Labels: bug, outreachy, testing

#8881 Testing: Post Replies with Multiple Comment Boxes Open
  test/fixtures/comments.yml
  test/fixtures/node_tags.yml
  test/fixtures/nodes.yml
  test/fixtures/revisions.yml
  test/functional/home_controller_test.rb
  test/functional/notes_controller_test.rb
  test/system/comment_test.rb
  test/unit/node_test.rb
Labels: outreachy, testing

#8879 Testing: Post Full Page, Then Immediately Comment
  test/system/comment_test.rb
Labels: outreachy, testing

#8935 [Outreachy ] New dashboard design
  app/controllers/home_controller.rb
  app/controllers/subscription_controller.rb
  app/views/dashboard/dashboard_v2.html.erb
  app/views/dashboard_v2/_blog.html.erb
  app/views/dashboard_v2/_header.html.erb
  app/views/dashboard_v2/_topicCard.html.erb
  app/views/dashboard_v2/dashboard.html.erb
  app/views/sidebar/_dashboard_v2.html.erb
  config/locales/en.yml
  test/fixtures/tag_selections.yml
  test/fixtures/tags.yml
  test/functional/home_controller_test.rb
  test/functional/subscription_controller_test.rb
  test/unit/subscription_location_test.rb
  test/unit/user_test.rb
Labels: outreachy

#8897 Bug: Fix Image Drag & Drop Cross-Wiring in Edit Comment Form
  app/assets/javascripts/atwho_autocomplete.js
  app/assets/javascripts/comment.js
  app/assets/javascripts/dragdrop.js
  app/assets/javascripts/editor.js
  app/helpers/application_helper.rb
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  app/views/wiki/edit.html.erb
  test/application_system_test_case.rb
  test/system/comment_test.rb
Labels: outreachy, testing

#8987 Bug: Fix CLICK-to-Upload Image Cross-Wiring Issues
  app/assets/javascripts/dragdrop.js
  app/assets/javascripts/editor.js
  test/fixtures/comments.yml
  test/system/comment_test.rb
Labels: bug, outreachy, testing

#9007 [Outreachy]Topic Cards Display And Count
  app/views/dashboard_v2/_topicCard.html.erb
Labels: readytomerge

#9012 Feature: Add Unique Preview Button IDs
  app/assets/javascripts/comment.js
  app/assets/javascripts/editor.js
  app/assets/stylesheets/editor.css
  app/helpers/application_helper.rb
  app/views/comments/_form.html.erb
  app/views/editor/_editor.html.erb
  config/locales/en.yml
  test/system/comment_test.rb
  test/system/post_test.rb
Labels: feature, outreachy, readytomerge

#9011 Bug: Fix Rich-Text Cross-Wiring in Comment Forms
  app/assets/javascripts/application.js
  app/assets/javascripts/dragdrop.js
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorHelper.js
  app/views/editor/_toolbar.html.erb
  app/views/notes/_comment.html.erb
  test/system/comment_test.rb
Labels: bug, outreachy, readytomerge

#9019 Bug: Show Image Upload Progress Bars in Edit Comment CLICK-to-Upload
  app/assets/javascripts/dragdrop.js
  app/assets/stylesheets/editor.css
  app/assets/stylesheets/question.css
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  test/system/comment_test.rb
Labels: JavaScript, bug, outreachy, readytomerge

#9035 Feature: Add setState Method in editor.js
  app/assets/javascripts/dragdrop.js
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorHelper.js
  app/views/comments/_edit.html.erb
  app/views/editor/_editor.html.erb
  test/system/comment_test.rb
Labels: JavaScript, feature, outreachy, readytomerge

#9037 Feature: Reorganize comment.js & dragdrop.js Script-Loading
  app/assets/javascripts/comment.js
  app/views/comments/_form.html.erb
  app/views/notes/_comments.html.erb
  app/views/questions/show.html.erb
  app/views/wiki/show.html.erb
Labels: JavaScript, feature, outreachy, readytomerge

#9045 Increase System Tests Speed by Decreasing Coverage
  test/system/comment_test.rb
Labels: outreachy, testing

#9044 Rename dragdrop.js to editorToolbar.js (Outreachy)
  app/assets/javascripts/application.js
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorHelper.js
  app/assets/javascripts/editorToolbar.js
  app/views/admin/assets.html.erb
  app/views/editor/post.html.erb
  app/views/editor/question.html.erb
  app/views/features/_form.html.erb
  app/views/map/edit.html.erb
  app/views/notes/_comments.html.erb
  app/views/questions/show.html.erb
  app/views/users/_photo.html.erb
  app/views/wiki/edit.html.erb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/staging_unstable.rb
  config/initializers/assets.rb
Labels: JavaScript, feature, outreachy, readytomerge

#9062 Add Unique IDs to Comment Forms
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorToolbar.js
  app/helpers/application_helper.rb
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  app/views/editor/_editor.html.erb
  app/views/notes/_comment.html.erb
  test/system/comment_test.rb
  test/system/post_test.rb
Labels: JavaScript, feature, outreachy, readytomerge

#9067 Integrate Edit Comment Form JavaScript with editor.js
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  app/views/notes/_comment.html.erb
  app/views/notes/show.html.erb
  app/views/questions/show.html.erb
  test/system/comment_test.rb
Labels: JavaScript, feature, outreachy, readytomerge

#9079 Style Fixes for _comment.html.erb Partial
  app/views/comments/_edit.html.erb
  app/views/notes/_comment.html.erb
  test/system/comment_test.rb
Labels: CSS, outreachy
