Repository publiclab/plots2, pull requests merged in 2021-03, with the labels that each got.

#9234 Hide <textarea> When Toggling Preview in Legacy Editor
  app/assets/javascripts/editor.js
  app/views/editor/_editor.html.erb
  config/locales/en.yml
  test/system/post_test.rb
Labels: JavaScript, bug, outreachy, readytomerge

#9329 remove "place" and "tool" from tag.rb file #9307
  app/models/tag.rb
Labels: readytomerge

#9176 Rewrite Comment Editor with React, install Webpack and React
  .browserslistrc
  .github/workflows/tests.yml
  .gitignore
  .gitpod.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  Makefile
  app/controllers/comment_controller.rb
  app/controllers/notes_controller.rb
  app/helpers/comment_helper.rb
  app/javascript/components/.keep
  app/javascript/components/App.js
  app/javascript/components/Comment.js
  app/javascript/components/CommentDisplay.js
  app/javascript/components/CommentForm.js
  app/javascript/components/CommentHeader.js
  app/javascript/components/CommentReplies.js
  app/javascript/components/CommentToolbar.js
  app/javascript/components/CommentToolbarButton.js
  app/javascript/components/CommentsContainer.js
  app/javascript/components/CommentsHeader.js
  app/javascript/components/CommentsList.js
  app/javascript/components/REACT_COMMENTS.md
  app/javascript/components/helpers.js
  app/javascript/components/static-props-context.js
  app/javascript/components/user-context.js
  app/javascript/packs/application.js
  app/javascript/packs/hello_react.jsx
  app/javascript/packs/server_rendering.js
  app/views/layouts/application.html.erb
  app/views/notes/show.html.erb
  babel.config.js
  bin/webpack
  bin/webpack-dev-server
  config/routes.rb
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/production.js
  config/webpack/test.js
  config/webpacker.yml
  package.json
  postcss.config.js
  yarn.lock
Labels: JavaScript, feature, outreachy

#9349 Deliver_now-DeliverLater-AdminController
  app/controllers/admin_controller.rb
Labels: readytomerge

#9367 Update settings.html.erb translation line
  app/views/users/settings.html.erb
Labels: readytomerge
