Repository publiclab/plots2, pull requests merged in 2021-06, with the labels that each got.

#9713 Add Test for React Edit Comment
  app/javascript/components/CommentToolbarButton.js
  app/javascript/components/CommentsList.js
  test/system/comment_test.rb
Labels: JavaScript, outreachy, react, readytomerge

#9715 Add Test for React Delete Comment
  app/views/notes/_comment.html.erb
  test/system/comment_test.rb
Labels: JavaScript, outreachy, react, readytomerge, testing

#9726 Fixed bug in advanced tagging menu
  app/views/tag/_advanced_tagging.html.erb
Labels: outreachy, readytomerge

#9709 Created a locked tag which can be added to notes by mods / admin
  app/assets/javascripts/tagging.js
  app/controllers/tag_controller.rb
  app/views/notes/show.html.erb
Labels: outreachy

#9696 Translation helper improvement (added html parameter)
  app/helpers/application_helper.rb
  app/views/dashboard/_wiki.html.erb
  app/views/home/subscriptions.html.erb
  app/views/layouts/_header.html.erb
  app/views/tag/_form.html.erb
  app/views/users/reset.html.erb
Labels: readytomerge

#9757 Tags added by banned users are not displayed
  app/views/tag/_tags.html.erb
Labels: outreachy, readytomerge

#9733 Normal users can't add tags on locked content
  app/views/notes/show.html.erb
  app/views/tag/_form.html.erb
Labels: outreachy, readytomerge

#9735 Added auto-labelling to PRs
  .github/workflows/tests.yml
Labels: readytomerge

#9751 Add React PropTypes for Array and Object Props
  app/javascript/components/App.js
  app/javascript/components/CommentReplies.js
  app/javascript/components/CommentsContainer.js
  app/javascript/components/CommentsList.js
Labels: JavaScript, outreachy, react, readytomerge

#9384 Added animation to save icon when user enters a comment text
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorToolbar.js
  test/system/comment_test.rb
Labels: readytomerge

#9801 Implement useReducer for Comment State Management
  app/javascript/components/CommentsContainer.js
  app/javascript/components/reducers.js
Labels: JavaScript, outreachy, react, readytomerge

#9772 Tests for tag locking
  app/controllers/tag_controller.rb
  app/models/node.rb
  test/functional/tag_controller_test.rb
Labels: outreachy

#9841 Update questionRich.html.erb
  app/views/editor/questionRich.html.erb
Labels: ready-for-review

#9849 Power tags are displayed as mini cards in the sidebar
  app/views/tag/_miniCard.html.erb
  app/views/tag/_tags.html.erb
  test/system/post_test.rb
Labels: outreachy

#9851 functional and system tests for preventing adding tags by first-time-posters
  test/functional/tag_controller_test.rb
  test/system/tag_test.rb
Labels: gsoc, testing

#9868 Try saving system test screenshots in GitHub Actions
  .github/workflows/tests.yml
Labels: ready-for-review

#9837 Add drafts link to profile page
  app/models/user.rb
  app/views/users/profile.html.erb
  test/unit/user_test.rb
Labels: readytomerge

#9862 Implement useReducer for commentFormsVisibility
  app/javascript/components/App.js
  app/javascript/components/CommentReplies.js
  app/javascript/components/CommentsContainer.js
  app/javascript/components/CommentsList.js
  app/javascript/components/helpers.js
  app/javascript/components/reducers.js
Labels: JavaScript, outreachy, react, readytomerge
