Repository publiclab/plots2, pull requests merged in 2021-08, with the labels that each got.

#9966 Revert "change webpacker.yml to see public/lib"
  config/webpacker.yml
Labels: ready-for-review

#9752 Prune Comment System Tests for Faster CI
  .github/workflows/tests.yml
  codecov.yml
  test/comment_system_tests/comment_test.rb
Labels: outreachy, testing

#9976 Standardize tooltips on row of icons
  app/views/like/_like.html.erb
Labels: outreachy

#9989 Adjust timestamp and URL correctly for draft publication
  app/controllers/notes_controller.rb
Labels: ready-for-review

#9994 Commenting some of the lines
  .github/PULL_REQUEST_TEMPLATE.md
Labels: readytomerge

#9992 LOGO of supporter UPDATED
  app/assets/images/logos/TravisCI-Full-Color.png
  app/assets/images/logos/codecov.png
  app/assets/images/logos/coveralls.png
  app/assets/images/logos/github_actions.png
  doc/SUPPORTERS.md
Labels: readytomerge

#9972 Sidebar powertag improvisations
  app/views/tag/_miniCard.html.erb
  app/views/tag/_tags.html.erb
Labels: outreachy, readytomerge

#10027 Add instructions to check translation changes
  db/seeds.rb
Labels: readytomerge, ready-for-review

#10036 Replace default dashboard with v2
  app/views/dashboard_v2/_sidebar.html.erb
  app/views/dashboard_v2/_topicCard.html.erb
  app/views/dashboard_v2/dashboard.html.erb
  config/routes.rb
  test/integration/I18n_test.rb
  test/system/dashboard_test.rb
  test/system/dashboard_v2_test.rb
Labels: ready-for-review

#9558 Scroll to top button disappears when on top
  app/assets/javascripts/headerFooter.js
Labels: readytomerge

#10037 Fix to Issue #10035 Update to Translation Call
  app/views/comments/_form.html.erb
Labels: readytomerge

#10042 Update post.html.erb with translation change
  app/views/editor/post.html.erb
Labels: readytomerge

#10081 Fix dashboard page title
  app/controllers/home_controller.rb
Labels: ready-for-review

#9958 Fixes to profile images for fog/Google Cloud Storage
  app/models/user.rb
Labels: ready-for-review

#10093 Fixes #9950 - 2 translation files
  app/views/layouts/_header.html.erb
  config/locales/en.yml
Labels: readytomerge

#10041 Fixing a gpg rvm.io install step with input from a newcomer
  README.md
Labels: ready-for-review

#10086 Translation question string
  app/views/editor/question.html.erb
Labels: readytomerge

#10122 add PDF to images fixtures and fix PDF upload display
  app/controllers/images_controller.rb
  test/fixtures/images.yml
  test/functional/images_controller_test.rb
Labels: ready-for-review

#10077 Changed "Ask a Question" String to Translation Function Call" #10075
  app/views/editor/questionRich.html.erb
  config/locales/en.yml
Labels: readytomerge
