Repository publiclab/plots2, pull requests merged in 2021-07, with the labels that each got.

#9881 Try locking tag records while updating their "activity_timestamp" field
  app/models/tag.rb
Labels: ready-for-review

#9863 Follow up to #9849 - 2 normal tag cards and 1 power tag card shows up in the sidebar
  app/views/tag/_tags.html.erb
  test/system/post_test.rb
Labels: outreachy, readytomerge

#9890 Corrected Greek YAML file langauge code
  config/locales/gr.yml
Labels: ready-for-review

#9889 Differentiate between normal tags and power tags
  app/views/tag/_tags.html.erb
Labels: outreachy, readytomerge

#9893 created drafts page
  app/controllers/notes_controller.rb
  app/views/notes/_nav_tabs.html.erb
  app/views/notes/drafts.html.erb
  app/views/users/profile.html.erb
  config/locales/en.yml
  config/routes.rb
  test/functional/notes_controller_test.rb
Labels: readytomerge

#9905 Create .codecov.yml
  .github/workflows/merge-pr.yml
  codecov.yml
Labels: ready-for-review

#9910 Update action.yml
  .github/merge-pr/action.yml
Labels: work-in-progress

#9915 Update merge-pr.yml
  .github/workflows/merge-pr.yml
  .github/workflows/tests.yml
Labels: work-in-progress

#9916 Trigger extra CI after merge to main branch, on workflow completion only
  .github/workflows/tests.yml
Labels: work-in-progress

#9807 switch image.rb to google storage via fog library
  Gemfile
  Gemfile.lock
  app/models/image.rb
  config/initializers/paperclip.rb
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
Labels: ready-for-review

#9917 add wait_for_ajax for barnstar errors (2nd attempt)
  codecov.yml
  test/system/post_test.rb
Labels: ready-for-review

#9878 Verify Translation in Development
  app/controllers/user_tags_controller.rb
  app/views/layouts/_header.html.erb
  test/integration/routes_test.rb
Labels: ready-for-review

#9929 comment markup rework for images etc in comments
  app/models/concerns/comments_shared.rb
  app/views/comment_mailer/notify.html.erb
  app/views/comment_mailer/notify_note_author.html.erb
  app/views/comment_mailer/notify_tag_followers.html.erb
Labels: ready-for-review

#9937 Update about us
  app/views/layouts/_header.html.erb
Labels: ready-for-review

#9931 Update and rename merge-pr.yml to merge-pr-sentry-release.yml
  .github/workflows/merge-pr-sentry-release.yml
  .github/workflows/merge-pr.yml
Labels: ready-for-review

#9947 Update _header.html.erb
  app/views/layouts/_header.html.erb
Labels: readytomerge

#9956 Update merge-pr-sentry-release.yml to change sentry environment to "staging"
  .github/workflows/merge-pr-sentry-release.yml
Labels: ready-for-review

#9959 change webpacker.yml to see public/lib
  config/webpacker.yml
Labels: ready-for-review

#9960 Completes pass-through of environment to Sentry via COMPOSE_PROJECT_NAME env var
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
  containers/docker-compose-testing.yml
  containers/docker-compose-unstable.yml
Labels: ready-for-review

#9973 Fixed tag input bar on profile page
  app/views/tag/_form.html.erb
Labels: readytomerge

#9922 Refactor question card
  app/views/notes/_card.html.erb
  app/views/questions/_questions.html.erb
Labels: outreachy
