Repository publiclab/plots2, pull requests merged in 2021-02, with the labels that each got.

#9104 Refactor editor.js with Object-Oriented Principles
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorToolbar.js
  app/assets/javascripts/post.js
  app/views/editor/_editor.html.erb
  app/views/notes/_comments.html.erb
  app/views/notes/show.html.erb
  app/views/questions/show.html.erb
  app/views/wiki/show.html.erb
Labels: JavaScript, feature, outreachy, readytomerge

#9107 Rewrite $E.setState for Single ID Parameter
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorToolbar.js
  app/helpers/application_helper.rb
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  app/views/editor/_editor.html.erb
  app/views/editor/_toolbar.html.erb
  app/views/map/edit.html.erb
  test/functional/editor_controller_test.rb
  test/functional/wiki_controller_test.rb
  test/system/comment_test.rb
  test/system/post_test.rb
Labels: JavaScript, feature, outreachy, readytomerge

#9108 Prune Editor State Management
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorToolbar.js
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  test/system/comment_test.rb
Labels: JavaScript, feature, outreachy, readytomerge

#9110 Refactor Editor Constructor and Methods, Write Editor Getters
  app/assets/javascripts/editor.js
  app/assets/javascripts/post.js
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  app/views/editor/_editor.html.erb
  test/system/post_test.rb
Labels: JavaScript, feature, outreachy

#9118 Disable Drag & Drop Upload on the Image Toolbar Button
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorToolbar.js
  app/assets/javascripts/post.js
  app/views/comments/_form.html.erb
  app/views/editor/_editor.html.erb
  app/views/editor/_toolbar.html.erb
  test/system/comment_test.rb
  test/system/post_test.rb
Labels: JavaScript, outreachy, readytomerge

#9123 Change #dropzone-large ID to #comment-form-body
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorToolbar.js
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  test/system/comment_test.rb
Labels: JavaScript, outreachy, readytomerge

#9132 Refactor Comment Editor Save & Recover
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorToolbar.js
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  app/views/editor/_editor.html.erb
  app/views/editor/_toolbar.html.erb
  app/views/notes/_comment.html.erb
  test/system/comment_test.rb
Labels: JavaScript, feature, outreachy, readytomerge

#9139 [System Tests] Save & Recover Buttons
  test/system/comment_test.rb
Labels: JavaScript, outreachy, readytomerge, testing

#9156 Changes to the header_footer.js filename
  app/assets/javascripts/application.js
  app/assets/javascripts/headerFooter.js
Labels: readytomerge

#9162 Fix Rich-Text & Image Upload in FRESHLY Posted Comments
  app/assets/javascripts/editor.js
  app/assets/javascripts/editorToolbar.js
  app/views/comments/create.js.erb
  app/views/editor/_editor.html.erb
  app/views/editor/post.html.erb
  app/views/editor/question.html.erb
  app/views/features/_form.html.erb
  app/views/notes/show.html.erb
  app/views/questions/show.html.erb
  app/views/wiki/_header.html.erb
  app/views/wiki/edit.html.erb
  app/views/wiki/show.html.erb
  test/system/comment_test.rb
Labels: JavaScript, bug, outreachy, readytomerge, testing

#9157 camelCase - submitFormAjax.js
  app/assets/javascripts/application.js
  app/assets/javascripts/submitFormAjax.js
Labels: readytomerge

#9163 camelCase advanced_search.js filename
  app/assets/javascripts/advancedSearch.js
  app/views/admin/assets.html.erb
  config/initializers/assets.rb
Labels: readytomerge

#9194 Rename async_tag_subscriptions.js to asyncTagSubscriptions.js
  app/assets/javascripts/asyncTagSubscriptions.js
  app/views/dashboard_v2/_sidebar.html.erb
  app/views/tag/index.html.erb
  config/initializers/assets.rb
Labels: readytomerge

#9183 Merge comments/edit & comments/form Partials
  app/assets/javascripts/comment.js
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  app/views/editor/_toolbar.html.erb
  app/views/notes/_comment.html.erb
Labels: JavaScript, outreachy, readytomerge

#9195 Refactor & Add Comments to create.js.erb; Style Fixes for Question Comments & Toolbar Buttons
  app/views/comments/create.js.erb
  app/views/editor/_toolbar.html.erb
  app/views/questions/show.html.erb
Labels: CSS, JavaScript, outreachy, readytomerge

#9186 Changed leaflet_helper.js to leafletHelper.js
  app/assets/javascripts/application.js
  app/assets/javascripts/leafletHelper.js
  app/assets/javascripts/timeago.js
Labels: readytomerge

#9198 Add Tooltips to Fresh Comments
  app/views/comments/_form.html.erb
  app/views/comments/create.js.erb
  app/views/notes/_comment.html.erb
  app/views/notes/_comments.html.erb
  app/views/questions/show.html.erb
  app/views/wiki/show.html.erb
Labels: JavaScript, outreachy, readytomerge

#9206 Fix comment_expand to camelcase
  app/assets/javascripts/commentExpand.js
  app/views/admin/assets.html.erb
  app/views/questions/show.html.erb
  config/initializers/assets.rb
  spec/javascripts/comment_spec.js
Labels: readytomerge

#9201 Rename main_image.js to mainImage.js
  app/assets/javascripts/application.js
  app/assets/javascripts/mainImage.js
Labels: readytomerge

#9216 [Outreachy]Add New Activity Columns in The Schema.Rb.Example File
  db/schema.rb.example
Labels: readytomerge

#9202 [Outreachy]Add Nearby Activity
  app/assets/javascripts/leafletHelper.js
  app/models/user.rb
  app/views/dashboard_v2/_location.html.erb
  app/views/dashboard_v2/_sidebar.html.erb
  config/locales/en.yml
  config/routes.rb
  test/functional/home_controller_test.rb
  test/system/dashboard_v2_test.rb
Labels: readytomerge

#9217 Change Add location to Nearby Activity if location tag exists
  app/views/sidebar/_dashboard.html.erb
Labels: readytomerge

#9225 camelCase noty_notification.js
  app/assets/javascripts/application.js
  app/assets/javascripts/notyNotification.js
Labels: readytomerge

#9221 Fix for preview button
  app/views/editor/post.html.erb
  app/views/editor/question.html.erb
  app/views/features/_form.html.erb
  app/views/wiki/edit.html.erb
Labels: readytomerge

#9228 Rename restful typeahead
  app/assets/javascripts/application.js
  app/assets/javascripts/restfulTypeahead.js
Labels: readytomerge

#7939 Minify bootstrap slider script and add defer tag
  app/views/layouts/application.html.erb
Labels: in-progress

#9133 Updated _form.html.erb
  app/views/locations/_form.html.erb
Labels: readytomerge

#4575 removed dynamic form (holding)
  config/initializers/dynamic_form.rb
  lib/dynamic_form/action_view/helpers/dynamic_form.rb
  lib/dynamic_form/action_view/locale/en.yml
  lib/dynamic_form/dynamic_form.rb
Labels: in progress
