Repository publiclab/plots2, pull requests merged in 2021-10, with the labels that each got.

#10167 Fix `.alert-success` System Test Error
  test/system/post_test.rb
Labels: testing

#10222 added Hacktoberfest content to readme.md
  README.md
Labels: hacktoberfest-accepted

#10226 Updated _miniCard.html.erb with translation strings
  app/views/tag/_miniCard.html.erb
Labels: hacktoberfest-accepted

#10232 Fixed #10208: Add Strings to Translation Function Call in questionRic…
  app/views/editor/questionRich.html.erb
  config/locales/en.yml
Labels: hacktoberfest-accepted

#10233 Updated the file index.html.erb with translation helper
  app/views/stats/index.html.erb
Labels: hacktoberfest-accepted

#10240 Added route test for openid
  test/integration/routes_test.rb
Labels: hacktoberfest-accepted

#10242 Added route test for create images
  test/integration/routes_test.rb
Labels: hacktoberfest-accepted

#10160 Update _header.html.erb
  app/views/layouts/_header.html.erb
Labels: readytomerge

#10254 move legacy dash to /research and redirect /v1/dashboard to /research for logged-in users
  app/controllers/home_controller.rb
  app/views/dashboard_v2/_sidebar.html.erb
  test/functional/home_controller_test.rb
Labels: ready-for-review

#10243 Added route test for create user sessions
  test/integration/routes_test.rb
Labels: hacktoberfest-accepted

#10257 Change post-merge Github Actions trigger
  .github/workflows/tests.yml
Labels: ready-for-review

#10454 fix tag test timestamp failures by moving off Time.now by 1 day into future
  test/system/post_test.rb
  test/unit/tag_test.rb
Labels: ready-for-review
