Repository publiclab/plots2, pull requests merged in 2022-01, with the labels that each got.

#10616 Update comment-artifacts.yml
  .github/workflows/comment-artifacts.yml
Labels: work-in-progress

#10619 Update comment-artifacts.yml
  .github/workflows/comment-artifacts.yml
Labels: work-in-progress

#10620 use " tonyhallett/artifacts-url-comments"
  .github/workflows/comment-artifacts.yml
Labels: ready-for-review

#10629 Reverse order of users in tag contributors/followers lists
  app/models/tag.rb
Labels: readytomerge, ready-for-review

#10604 Update edit profile form field validation and password visibility
  app/assets/javascripts/validation.js
  app/views/users/_edit_form.html.erb
Labels: readytomerge, ready-for-review

#10630 Pin ruby to 2.7.3 in .gitpod.dockerfile
  .gitpod.dockerfile
Labels: readytomerge, ready-for-review

#10633 Fix: updated First timers issue template url and changed the location of "templet for opening a issue".
  CONTRIBUTING.md
  README.md
Labels: readytomerge, ready-for-review

#10637 Hide sort dropdown for tag comments in show.html.erb
  app/views/tag/show.html.erb
Labels: readytomerge, ready-for-review

#10661 Added strings to Translation file
  app/views/tag/show/_tab_content.html.erb
  config/locales/en.yml
Labels: readytomerge, ready-for-review

#10658 Add strings to Translation File - _advanced_tagging.html.erb
  config/locales/en.yml
Labels: readytomerge, ready-for-review

#10659 Fixed:Add strings to Translation File-Issue#10656
  app/views/tag/_advanced_tagging.html.erb
Labels: readytomerge, ready-for-review

#10652 update LABELS.md
  doc/LABELS.md
Labels: ready-for-review
