Repository publiclab/plots2, pull requests merged in 2022-04, with the labels that each got.

#10910 Add mysql2 warning to README
  README.md
Labels: readytomerge, ready-for-review

#10906 changed "distance_in_words:" to "time_ago_in_words:"
  config/locales/ru.yml
Labels: readytomerge, ready-for-review

#10903 Change translation key for distance_of_time_on_words
  config/locales/es.yml
Labels: readytomerge, ready-for-review

#10889 Changed the color of comment icon at Event Page
  app/views/wiki/_header.html.erb
Labels: readytomerge, ready-for-review

#10936 Update profile.html.erb - show the cancel button only to logged in users, admins/moderators and profile users.
  app/views/users/profile.html.erb
Labels: readytomerge, ready-for-review

#10902 Remove Duplicate Code In Spam 2 queue
  app/views/spam2/_queue.html.erb
Labels: readytomerge, ready-for-review

#10880 Update default image for question cards on tag page #10880
  app/views/questions/_new_question.html.erb
Labels: readytomerge, ready-for-review

#10877 updated rubocop_shopify_style_guide and related files
  .rubocop.yml
  .rubocop_shopify_styleguide.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
Labels: readytomerge, ready-for-review

#10926 Remove Duplicate Code in Spam2 flags
  app/views/spam2/_flags.html.erb
Labels: readytomerge, ready-for-review

#10951 removed duplicate code in spam 2 users
  app/views/spam2/_users.html.erb
Labels: readytomerge, ready-for-review

#10953 Added tooltips in icons on wiki page header
  app/views/wiki/_header.html.erb
Labels: readytomerge, ready-for-review

#10940 Fixes #10922 Updated to use length.positive
  app/mailers/subscription_mailer.rb
Labels: readytomerge, ready-for-review

#10943 #10917 Update _header.html.erb
  app/views/wiki/_header.html.erb
Labels: readytomerge, ready-for-review

#10876 added unflag-tooltip to claify button
  app/views/spam2/_flags.html.erb
Labels: readytomerge, ready-for-review

#10972 updated search.rb by replacing : usage with ||
  app/api/srch/search.rb
Labels: readytomerge, ready-for-review

#10980 Update README.md
  README.md
Labels: readytomerge, ready-for-review

#11031 Fixed warnings in style.css file
  static/style.css
Labels: readytomerge, ready-for-review

#11024 Update search.rb
  app/api/srch/search.rb
Labels: readytomerge, ready-for-review

#11015 Corrected indentation comments.html.erb
  app/views/spam2/_comments.html.erb
Labels: readytomerge, ready-for-review

#11011 corrected hidden
  app/views/spam2/_spam.html.erb
Labels: readytomerge, ready-for-review

#11008 add meta tag to warn bots not to index revision pages
  app/views/layouts/application.html.erb
Labels: readytomerge, ready-for-review

#11045 Fix yarn.lock grow-textarea git://
  yarn.lock
Labels: ready-for-review

#11046 Second git+https protocol fix
  yarn.lock
Labels: ready-for-review

#10891 Remove "Show More" button from tables
  app/views/grids/_notes.html.erb
  test/unit/node_shared_test.rb
Labels: readytomerge, ready-for-review

#11005 Allow mods and admins to see all profile bios
  app/views/users/profile.html.erb
Labels: readytomerge, ready-for-review

#10967 Update on "Make Insights Table More Descriptive in Spam 2 #10959" issue
  app/views/spam2/_insights.html.erb
Labels: readytomerge, ready-for-review

#10981 Update DOCTYPE of static/index.html
  static/index.html
Labels: readytomerge, ready-for-review

#10802 Fixes #10677: Fixed profile picture on profile page
  app/views/users/profile.html.erb
Labels: readytomerge, ready-for-review

#11072 Disable Comment Form While Guest Browsing
  app/javascript/components/CommentsContainer.js
Labels: JavaScript, outreachy, readytomerge, react
