Repository publiclab/plots2, pull requests merged in 2022-03, with the labels that each got.

#10736 Add a limit to the docker container log.
  containers/docker-compose-production.yml
  containers/docker-compose-stable.yml
Labels: hotfix, ready-for-review

#10747 Fix indent
  containers/docker-compose-stable.yml
  containers/docker-compose-unstable.yml
Labels: work-in-progress

#10746 Update "blank" default image on cards and topic cards
  app/views/dashboard_v2/_topicCard.html.erb
  app/views/notes/_card.html.erb
Labels: ready-for-review

#10748 remove limit on user.normal_tags
  app/models/user.rb
Labels: ready-for-review

#10763 fixed pluralizaion error
  app/views/dashboard_v2/_topicCard.html.erb
Labels: ready-for-review

#10766 fix for unpaginated tag pages
  app/controllers/tag_controller.rb
Labels: ready-for-review

#10767 Update _signupLoginModal.html.erb
  app/views/layouts/_signupLoginModal.html.erb
Labels: readytomerge, ready-for-review

#10775 deactivated link to followers and following when they're 0
  app/views/users/profile.html.erb
  package.json
Labels: ready-for-review

#10735 Added css transition while toggling
  app/assets/javascripts/sidebar.js
  app/views/sidebar/_question.html.erb
Labels: readytomerge, ready-for-review

#10781 Making the little `v` button larger on /questions page
  app/views/sidebar/_question.html.erb
Labels: readytomerge, ready-for-review

#10821 Customize translation locale prompt to correct I18n.locale
  app/assets/javascripts/translation.js
  app/controllers/settings_controller.rb
  app/helpers/application_helper.rb
Labels: ready-for-review

#10787 Translation helper enabled for all pages
  app/views/dashboard/dashboard.html.erb
  app/views/home/subscriptions.html.erb
  app/views/layouts/application.html.erb
  app/views/users/profile.html.erb
  yarn.lock
Labels: Translation System, ready-for-review

#10867 Implement useReducer for textAreaValues
  app/javascript/components/Comment.js
  app/javascript/components/CommentsContainer.js
  app/javascript/components/CommentsList.js
  app/javascript/components/reducers.js
Labels: JavaScript, outreachy, readytomerge, react

#10870 refactored image.rb to use present instead of blank
  app/models/image.rb
Labels: readytomerge, ready-for-review

#10872 Add tooltip functionality to the locked icon on /events page
  app/views/like/_like.html.erb
Labels: readytomerge, ready-for-review

#10794 Fixes #6304: Added eye icon for contributors that are following too
  app/views/tag/_contributors.html.erb
Labels: readytomerge, ready-for-review
