Repository publiclab/plots2, pull requests merged in 2022-06, with the labels that each got.

#11166 Remove direct woofmark dependency
  package.json
Labels: ready-for-review

#11169 login form return_to fix
  app/views/user_sessions/_form.html.erb
Labels: ready-for-review

#11184 add rel="nofollow" to oauth links
  app/views/layouts/_social_icons.html.erb
Labels: ready-for-review

#11214 add system test for I18njs
  test/system/signup_form_test.rb
Labels: ready-for-review

#11084 Updated the file comment_helper.rb to change auto_link timing
  app/helpers/comment_helper.rb
Labels: readytomerge, ready-for-review

#11231 adding --frozen-lockfile to yarn commands
  Makefile
  start.sh
Labels: work-in-progress
